// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/serial/fdt_serial_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/serial/fdt_serial.h>

extern const struct fdt_driver fdt_serial_cadence;
extern const struct fdt_driver fdt_serial_gaisler;
extern const struct fdt_driver fdt_serial_htif;
extern const struct fdt_driver fdt_serial_renesas_scif;
extern const struct fdt_driver fdt_serial_shakti;
extern const struct fdt_driver fdt_serial_sifive;
extern const struct fdt_driver fdt_serial_litex;
extern const struct fdt_driver fdt_serial_uart8250;
extern const struct fdt_driver fdt_serial_xlnx_uartlite;

const struct fdt_driver *const fdt_serial_drivers[] = {
	&fdt_serial_cadence,
	&fdt_serial_gaisler,
	&fdt_serial_htif,
	&fdt_serial_renesas_scif,
	&fdt_serial_shakti,
	&fdt_serial_sifive,
	&fdt_serial_litex,
	&fdt_serial_uart8250,
	&fdt_serial_xlnx_uartlite,
	NULL
};
