#ifndef MPFR_CONFIG_H
#define MPFR_CONFIG_H

#define HAVE_ALLOCA 1
#define HAVE_ALLOCA_H 1
#define HAVE_ATTRIBUTE_CONST 1
#define HAVE_ATTRIBUTE_MODE 1
#define HAVE_BUILTIN_UNREACHABLE 1
#define HAVE_DOUBLE_IEEE_LITTLE_ENDIAN 1
#define HAVE_INTTYPES_H 1
#define HAVE_LITTLE_ENDIAN 1
#define HAVE_LOCALE_H 1
#define HAVE_LONG_LONG 1
#define HAVE_SETLOCALE 1
#define HAVE_STDARG 1
#define HAVE_STDINT_H 1
#define HAVE_STRUCT_LCONV_DECIMAL_POINT 1
#define HAVE_STRUCT_LCONV_THOUSANDS_SEP 1
#define HAVE_VA_COPY 1
#define HAVE_WCHAR_H 1
#define MPFR_HAVE_BUILTIN_UNREACHABLE 1
#define MPFR_HAVE_CONSTRUCTOR_ATTR 1
#define MPFR_HAVE_NORETURN 1
#define STDC_HEADERS 1

#endif
