// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/irqchip/fdt_irqchip_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/irqchip/fdt_irqchip.h>

extern struct fdt_irqchip fdt_irqchip_aplic;
extern struct fdt_irqchip fdt_irqchip_imsic;
extern struct fdt_irqchip fdt_irqchip_plic;

struct fdt_irqchip *const fdt_irqchip_drivers[] = {
	&fdt_irqchip_aplic,
	&fdt_irqchip_imsic,
	&fdt_irqchip_plic,
	NULL
};
