"""The binutils configuration of binutils 2.47, per platform of //:targets.bzl.

GENERATED by modules/binutils/generate_targets.py; do not edit.  Results
identical between platforms are shared, named after the first platform using them.
"""

visibility(["//..."])

_BINUTILS_LINUX_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-pc-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-pc-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-unknown-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_AARCH32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"arm-unknown-linux-gnueabi\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_ARMV7 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"armv7-unknown-linux-gnueabihf\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_PPC = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc64-unknown-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_PPC32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc-unknown-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_PPC64LE = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc64le-unknown-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_S390X = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"s390x-ibm-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_MIPS64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"mips64-unknown-linux-gnuabi64\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_RISCV32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"riscv32-unknown-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_LINUX_RISCV64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"riscv64-unknown-linux-gnu\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_ANDROID_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-pc-linux-android\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_ANDROID_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-pc-linux-android\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_ANDROID_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-unknown-linux-android\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_ANDROID_AARCH32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"arm-unknown-linux-androideabi\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_ANDROID_ARMV7 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"armv7-unknown-linux-androideabi\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_ANDROID_RISCV64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"riscv64-unknown-linux-android\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_WINDOWS_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-w64-mingw32\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [
        "DLLTOOL_MX86_64",
        "DLLTOOL_DEFAULT_MX86_64",
    ],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\" &objdump_private_desc_pe,\"",
    ],
    "od_srcs": [
        "od-pe.c",
    ],
}

_BINUTILS_WINDOWS_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-w64-mingw32\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=1",
    ],
    "dlltool_defs": [
        "DLLTOOL_I386",
        "DLLTOOL_DEFAULT_I386",
    ],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\" &objdump_private_desc_pe,\"",
    ],
    "od_srcs": [
        "od-pe.c",
    ],
}

_BINUTILS_WINDOWS_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-w64-mingw32\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [
        "DLLTOOL_AARCH64",
        "DLLTOOL_DEFAULT_AARCH64",
    ],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\" &objdump_private_desc_pe,\"",
    ],
    "od_srcs": [
        "od-pe.c",
    ],
}

_BINUTILS_MACOS_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-apple-darwin\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\" &objdump_private_desc_mach_o,\"",
    ],
    "od_srcs": [
        "od-macho.c",
    ],
}

_BINUTILS_MACOS_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-apple-darwin\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\" &objdump_private_desc_mach_o,\"",
    ],
    "od_srcs": [
        "od-macho.c",
    ],
}

_BINUTILS_FREEBSD_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-pc-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-pc-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_AARCH32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"arm-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_ARMV7 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"armv7-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_PPC = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc64-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_PPC32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_PPC64LE = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc64le-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_MIPS64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"mips64-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FREEBSD_RISCV64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"riscv64-unknown-freebsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-pc-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-pc-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-unknown-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_AARCH32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"arm-unknown-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_PPC = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc64-unknown-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_PPC32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc-unknown-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_MIPS64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"mips64-unknown-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_NETBSD_RISCV64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"riscv64-unknown-netbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-pc-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-pc-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-unknown-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_AARCH32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"arm-unknown-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_PPC = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc64-unknown-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_PPC32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc-unknown-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_MIPS64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"mips64-unknown-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_OPENBSD_RISCV64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"riscv64-unknown-openbsd\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_HAIKU_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-unknown-haiku\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_HAIKU_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-unknown-haiku\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_VXWORKS_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-wrs-vxworks\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=1",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_VXWORKS_AARCH32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"arm-wrs-vxworks\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_VXWORKS_PPC32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc-wrs-vxworks\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_VXWORKS_MIPS64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"mips64-wrs-vxworks\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_QNX_X86_32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"i686-pc-nto-qnx\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_QNX_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-pc-nto-qnx\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_QNX_AARCH32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"arm-pc-nto-qnx\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_QNX_PPC32 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"powerpc-pc-nto-qnx\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FUCHSIA_X86_64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"x86_64-unknown-fuchsia\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FUCHSIA_AARCH64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"aarch64-unknown-fuchsia\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

_BINUTILS_FUCHSIA_RISCV64 = {
    "defines": [
        "bin_dummy_emulation=bin_vanilla_emulation",
        "TARGET=\"\\\"riscv64-unknown-fuchsia\\\"\"",
        "TARGET_PREPENDS_UNDERSCORE=0",
    ],
    "dlltool_defs": [],
    "emul_srcs": [
        "emul_vanilla.c",
    ],
    "objdump_defs": [
        "OBJDUMP_PRIVATE_VECTORS=\"\"",
    ],
    "od_srcs": [],
}

BINUTILS = {
    "android_aarch32": _BINUTILS_ANDROID_AARCH32,
    "android_aarch64": _BINUTILS_ANDROID_AARCH64,
    "android_armv7": _BINUTILS_ANDROID_ARMV7,
    "android_i386": _BINUTILS_ANDROID_X86_32,
    "android_riscv64": _BINUTILS_ANDROID_RISCV64,
    "android_x86_32": _BINUTILS_ANDROID_X86_32,
    "android_x86_64": _BINUTILS_ANDROID_X86_64,
    "chromiumos_aarch32": _BINUTILS_LINUX_AARCH32,
    "chromiumos_aarch64": _BINUTILS_LINUX_AARCH64,
    "chromiumos_armv7": _BINUTILS_LINUX_ARMV7,
    "chromiumos_i386": _BINUTILS_LINUX_X86_32,
    "chromiumos_x86_32": _BINUTILS_LINUX_X86_32,
    "chromiumos_x86_64": _BINUTILS_LINUX_X86_64,
    "freebsd_aarch32": _BINUTILS_FREEBSD_AARCH32,
    "freebsd_aarch64": _BINUTILS_FREEBSD_AARCH64,
    "freebsd_armv7": _BINUTILS_FREEBSD_ARMV7,
    "freebsd_i386": _BINUTILS_FREEBSD_X86_32,
    "freebsd_mips64": _BINUTILS_FREEBSD_MIPS64,
    "freebsd_ppc": _BINUTILS_FREEBSD_PPC,
    "freebsd_ppc32": _BINUTILS_FREEBSD_PPC32,
    "freebsd_ppc64le": _BINUTILS_FREEBSD_PPC64LE,
    "freebsd_riscv64": _BINUTILS_FREEBSD_RISCV64,
    "freebsd_x86_32": _BINUTILS_FREEBSD_X86_32,
    "freebsd_x86_64": _BINUTILS_FREEBSD_X86_64,
    "fuchsia_aarch64": _BINUTILS_FUCHSIA_AARCH64,
    "fuchsia_riscv64": _BINUTILS_FUCHSIA_RISCV64,
    "fuchsia_x86_64": _BINUTILS_FUCHSIA_X86_64,
    "haiku_i386": _BINUTILS_HAIKU_X86_32,
    "haiku_x86_32": _BINUTILS_HAIKU_X86_32,
    "haiku_x86_64": _BINUTILS_HAIKU_X86_64,
    "linux_aarch32": _BINUTILS_LINUX_AARCH32,
    "linux_aarch64": _BINUTILS_LINUX_AARCH64,
    "linux_armv7": _BINUTILS_LINUX_ARMV7,
    "linux_i386": _BINUTILS_LINUX_X86_32,
    "linux_mips64": _BINUTILS_LINUX_MIPS64,
    "linux_ppc": _BINUTILS_LINUX_PPC,
    "linux_ppc32": _BINUTILS_LINUX_PPC32,
    "linux_ppc64le": _BINUTILS_LINUX_PPC64LE,
    "linux_riscv32": _BINUTILS_LINUX_RISCV32,
    "linux_riscv64": _BINUTILS_LINUX_RISCV64,
    "linux_s390x": _BINUTILS_LINUX_S390X,
    "linux_x86_32": _BINUTILS_LINUX_X86_32,
    "linux_x86_64": _BINUTILS_LINUX_X86_64,
    "macos_aarch64": _BINUTILS_MACOS_AARCH64,
    "macos_x86_64": _BINUTILS_MACOS_X86_64,
    "netbsd_aarch32": _BINUTILS_NETBSD_AARCH32,
    "netbsd_aarch64": _BINUTILS_NETBSD_AARCH64,
    "netbsd_armv7": _BINUTILS_NETBSD_AARCH32,
    "netbsd_i386": _BINUTILS_NETBSD_X86_32,
    "netbsd_mips64": _BINUTILS_NETBSD_MIPS64,
    "netbsd_ppc": _BINUTILS_NETBSD_PPC,
    "netbsd_ppc32": _BINUTILS_NETBSD_PPC32,
    "netbsd_riscv64": _BINUTILS_NETBSD_RISCV64,
    "netbsd_x86_32": _BINUTILS_NETBSD_X86_32,
    "netbsd_x86_64": _BINUTILS_NETBSD_X86_64,
    "nixos_aarch32": _BINUTILS_LINUX_AARCH32,
    "nixos_aarch64": _BINUTILS_LINUX_AARCH64,
    "nixos_armv7": _BINUTILS_LINUX_ARMV7,
    "nixos_i386": _BINUTILS_LINUX_X86_32,
    "nixos_mips64": _BINUTILS_LINUX_MIPS64,
    "nixos_ppc": _BINUTILS_LINUX_PPC,
    "nixos_ppc32": _BINUTILS_LINUX_PPC32,
    "nixos_ppc64le": _BINUTILS_LINUX_PPC64LE,
    "nixos_riscv32": _BINUTILS_LINUX_RISCV32,
    "nixos_riscv64": _BINUTILS_LINUX_RISCV64,
    "nixos_s390x": _BINUTILS_LINUX_S390X,
    "nixos_x86_32": _BINUTILS_LINUX_X86_32,
    "nixos_x86_64": _BINUTILS_LINUX_X86_64,
    "openbsd_aarch32": _BINUTILS_OPENBSD_AARCH32,
    "openbsd_aarch64": _BINUTILS_OPENBSD_AARCH64,
    "openbsd_armv7": _BINUTILS_OPENBSD_AARCH32,
    "openbsd_i386": _BINUTILS_OPENBSD_X86_32,
    "openbsd_mips64": _BINUTILS_OPENBSD_MIPS64,
    "openbsd_ppc": _BINUTILS_OPENBSD_PPC,
    "openbsd_ppc32": _BINUTILS_OPENBSD_PPC32,
    "openbsd_riscv64": _BINUTILS_OPENBSD_RISCV64,
    "openbsd_x86_32": _BINUTILS_OPENBSD_X86_32,
    "openbsd_x86_64": _BINUTILS_OPENBSD_X86_64,
    "qnx_aarch32": _BINUTILS_QNX_AARCH32,
    "qnx_aarch64": _BINUTILS_QNX_AARCH64,
    "qnx_armv7": _BINUTILS_QNX_AARCH32,
    "qnx_i386": _BINUTILS_QNX_X86_32,
    "qnx_ppc32": _BINUTILS_QNX_PPC32,
    "qnx_x86_32": _BINUTILS_QNX_X86_32,
    "vxworks_aarch32": _BINUTILS_VXWORKS_AARCH32,
    "vxworks_armv7": _BINUTILS_VXWORKS_AARCH32,
    "vxworks_i386": _BINUTILS_VXWORKS_X86_32,
    "vxworks_mips64": _BINUTILS_VXWORKS_MIPS64,
    "vxworks_ppc32": _BINUTILS_VXWORKS_PPC32,
    "vxworks_x86_32": _BINUTILS_VXWORKS_X86_32,
    "windows_aarch64": _BINUTILS_WINDOWS_AARCH64,
    "windows_i386": _BINUTILS_WINDOWS_X86_32,
    "windows_x86_32": _BINUTILS_WINDOWS_X86_32,
    "windows_x86_64": _BINUTILS_WINDOWS_X86_64,
}
