/*
 * Originally generated by `meson setup` for the systemd 260.1 build,
 * then sanitised: sandbox-specific paths under PREFIX/BINDIR/etc. were
 * replaced with /usr-style values. libudev does not read most of these
 * paths at runtime (they are referenced by systemd binaries we do not
 * build), so the exact values are mostly cosmetic.
 *
 * Regeneration recipe: bump systemd, run `meson setup` once, dump
 * config.h, replace the sandbox PREFIX with `/usr/lib/systemd` and trim.
 */

#pragma once

#define ADM_GID -

#define AGETTY "/usr/sbin/agetty"

#define ANSI_OK_COLOR ANSI_GREEN

#define AUDIO_GID -

#define BINDIR "/usr/bin"

#define BINFMT_DIR "/usr/lib/binfmt.d"

#define BOOTLIBDIR "/usr/lib/systemd/boot/efi"

#define BPF_FRAMEWORK 0

/* tailor build to development or release builds */
#define BUILD_MODE_DEVELOPER 1

#define BUMP_PROC_SYS_FS_FILE_MAX 1

#define BUMP_PROC_SYS_FS_NR_OPEN 1

#define CATALOG_DATABASE "/var/lib/systemd/catalog/database"

#define CDROM_GID -

#define CERTIFICATE_ROOT "/etc/ssl"

#define CLOCK_GID -

#define CLOCK_VALID_RANGE_USEC_MAX 473364000000000

#define COMPRESSION_PRIORITY_LZ4 "suggested"

#define COMPRESSION_PRIORITY_XZ "suggested"

#define COMPRESSION_PRIORITY_ZSTD "suggested"

#define CONTAINER_UID_BASE_MAX 1878982656

#define CONTAINER_UID_BASE_MIN 524288

#define CREATE_LOG_DIRS 1

#define CREATE_SSHDPRIVSEPDIR 1

#define CURL_NO_OLDIES 1

#define DEBUGTTY "/dev/tty9"

#define DEFAULT_COMPRESSION COMPRESSION_NONE

#define DEFAULT_DNSSEC_MODE DNSSEC_ALLOW_DOWNGRADE

#define DEFAULT_DNSSEC_MODE_STR "allow-downgrade"

#define DEFAULT_DNS_OVER_TLS_MODE DNS_OVER_TLS_NO

#define DEFAULT_DNS_OVER_TLS_MODE_STR "no"

#define DEFAULT_LLMNR_MODE RESOLVE_SUPPORT_YES

#define DEFAULT_LLMNR_MODE_STR "yes"

#define DEFAULT_MDNS_MODE RESOLVE_SUPPORT_YES

#define DEFAULT_MDNS_MODE_STR "yes"

#define DEFAULT_MOUNTFSD_TRUSTED_DIRECTORIES 0

/* Default naming scheme as a string */
#define DEFAULT_NET_NAMING_SCHEME "latest"

#define DEFAULT_TIMEOUT_SEC 90

#define DEFAULT_USER_SHELL "/bin/bash"

#define DEFAULT_USER_SHELL_NAME "bash"

#define DEFAULT_USER_TIMEOUT_SEC 90

#define DEV_KVM_MODE "0666"

#define DEV_KVM_UACCESS 0

#define DIALOUT_GID -

#define DISK_GID -

#define DNS_SERVERS "1.1.1.1#cloudflare-dns.com 8.8.8.8#dns.google 9.9.9.9#dns.quad9.net 1.0.0.1#cloudflare-dns.com 8.8.4.4#dns.google 149.112.112.112#dns.quad9.net 2606:4700:4700::1111#cloudflare-dns.com 2001:4860:4860::8888#dns.google 2620:fe::fe#dns.quad9.net 2606:4700:4700::1001#cloudflare-dns.com 2001:4860:4860::8844#dns.google 2620:fe::9#dns.quad9.net"

#define DOCUMENT_ROOT "/usr/share/systemd/gatewayd"

#define DOC_DIR "/usr/share/doc/systemd"

#define DYNAMIC_UID_MAX 65519

#define DYNAMIC_UID_MIN 61184

#define EFI_MACHINE_TYPE_NAME ""

#define EMPOWER_GID -

#define ENABLE_ADM_GROUP 1

#define ENABLE_ANALYZE 1

#define ENABLE_BACKLIGHT 1

#define ENABLE_BINFMT 1

#define ENABLE_BOOTLOADER 0

#define ENABLE_COMPAT_MUTABLE_UID_BOUNDARIES 0

#define ENABLE_COMPAT_SYSV_INTERFACES 1

#define ENABLE_COREDUMP 1

#define ENABLE_DEBUG_HASHMAP 0

#define ENABLE_DEBUG_MMAP_CACHE 0

#define ENABLE_DEBUG_SIPHASH 0

#define ENABLE_DNS_OVER_TLS 1

#define ENABLE_EFI 1

#define ENABLE_ENVIRONMENT_D 1

#define ENABLE_FEXECVE 0

#define ENABLE_FIRSTBOOT 1

#define ENABLE_FIRST_BOOT_FULL_PRESET 0

#define ENABLE_GSHADOW 1

#define ENABLE_HIBERNATE 1

#define ENABLE_HOMED 0

#define ENABLE_HOSTNAMED 1

#define ENABLE_HWDB 1

#define ENABLE_IDN 1

#define ENABLE_IMA 1

#define ENABLE_IMPORTD 0

#define ENABLE_INITRD 1

#define ENABLE_IPE 1

#define ENABLE_KERNEL_INSTALL 1

#define ENABLE_LDCONFIG 1

#define ENABLE_LOCALED 1

#define ENABLE_LOGIND 1

#define ENABLE_MACHINED 1

#define ENABLE_MOUNTFSD 1

#define ENABLE_NETWORKD 1

#define ENABLE_NSPAWN 1

#define ENABLE_NSRESOURCED 1

#define ENABLE_NSS 1

#define ENABLE_NSS_MYHOSTNAME 1

#define ENABLE_NSS_MYMACHINES 1

#define ENABLE_NSS_RESOLVE 1

#define ENABLE_NSS_SYSTEMD 1

#define ENABLE_OOMD 1

#define ENABLE_PAM_HOME 0

#define ENABLE_POLKIT 1

#define ENABLE_PORTABLED 1

#define ENABLE_PSTORE 1

#define ENABLE_QUOTACHECK 1

#define ENABLE_RANDOMSEED 1

#define ENABLE_REMOTE 1

#define ENABLE_REPART 0

#define ENABLE_RESOLVE 1

#define ENABLE_RFKILL 1

#define ENABLE_SMACK 1

#define ENABLE_SSH_PROXY_CONFIG 1

#define ENABLE_SSH_USERDB_CONFIG 1

#define ENABLE_STORAGETM 1

#define ENABLE_SYSCTL_BPF 0

#define ENABLE_SYSEXT 1

#define ENABLE_SYSUPDATE 0

#define ENABLE_SYSUPDATED 0

#define ENABLE_SYSUSERS 1

#define ENABLE_TIMEDATECTL 1

#define ENABLE_TIMEDATED 1

#define ENABLE_TIMESYNCD 1

#define ENABLE_TMPFILES 1

#define ENABLE_TPM 1

#define ENABLE_UKIFY 0

#define ENABLE_URLIFY 1

#define ENABLE_USERDB 1

#define ENABLE_UTMP 1

#define ENABLE_VCONSOLE 1

#define ENABLE_VMSPAWN 1

#define ENABLE_WHEEL_GROUP 1

#define ENABLE_XDG_AUTOSTART 1

#define ENVIRONMENT_DIR "/usr/lib/environment.d"

#define EXTRA_NET_NAMING_MAP 

#define EXTRA_NET_NAMING_SCHEMES 

#define FALLBACK_HOSTNAME "localhost"

#define FOREIGN_UID_BASE 2147352576

#define FUZZ_USE_SIZE_LIMIT 0

#define GETTEXT_PACKAGE "systemd"

/* The type of gperf "len" parameter (size_t for gperf >= 3.1). */
#define GPERF_LEN_TYPE size_t

#define GREETER_UID_MAX 60705

#define GREETER_UID_MIN 60578

#define GROUP_RENDER_MODE "0666"

#define GROUP_RENDER_UACCESS 0

#define HAVE_ACL 0

#define HAVE_ADD_KEY 0

#define HAVE_APPARMOR 0

#define HAVE_ARCHIVE_ENTRY_GID_IS_SET 0

#define HAVE_ARCHIVE_ENTRY_HARDLINK_IS_SET 0

#define HAVE_ARCHIVE_ENTRY_UID_IS_SET 0

#define HAVE_AUDIT 0

#define HAVE_BLKID 0

#define HAVE_BPF 0

#define HAVE_BZIP2 0

#define HAVE_COMPRESSION 0

#define HAVE_CRYPT_SET_KEYRING_TO_LINK 0

#define HAVE_CRYPT_TOKEN_SET_EXTERNAL_PATH 0

#define HAVE_DBUS 0

#define HAVE_DMI 1

#define HAVE_DWFL_SET_SYSROOT 0

#define HAVE_ELFUTILS 0

#define HAVE_EPOLL_PWAIT2 1

#define HAVE_FCHMODAT2 0

#define HAVE_FSCONFIG 1

#define HAVE_FSMOUNT 1

#define HAVE_FSOPEN 1

#define HAVE_GCRYPT 0

#define HAVE_GET_MEMPOLICY 0

#define HAVE_GLIB 0

#define HAVE_GNUTLS 0

#define HAVE_IOPRIO_GET 0

#define HAVE_IOPRIO_SET 0

#define HAVE_KCMP 0

#define HAVE_KEYCTL 0

#define HAVE_KMOD 0

#define HAVE_LIBARCHIVE 0

#define HAVE_LIBBPF 0

#define HAVE_LIBCRYPT 0

#define HAVE_LIBCRYPTSETUP 0

#define HAVE_LIBCRYPTSETUP_PLUGINS 0

#define HAVE_LIBCURL 0

#define HAVE_LIBFDISK 0

#define HAVE_LIBFIDO2 0

#define HAVE_LIBIDN2 0

#define HAVE_LIBMOUNT 0

#define HAVE_LOCALEGEN 0

#define HAVE_LZ4 0

#define HAVE_MICROHTTPD 0

#define HAVE_MOUNT_SETATTR 1

#define HAVE_MOVE_MOUNT 1

#define HAVE_NI_IDN 1

#define HAVE_OPENSSL 1

#define HAVE_OPEN_TREE 1

#define HAVE_OPEN_TREE_ATTR 0

#define HAVE_P11KIT 0

#define HAVE_PAM 0

#define HAVE_PASSWDQC 0

#define HAVE_PCRE2 0

#define HAVE_PIDFD_OPEN 0

#define HAVE_PIDFD_SEND_SIGNAL 0

#define HAVE_PIDFD_SPAWN 0

#define HAVE_PIVOT_ROOT 0

#define HAVE_PWQUALITY 0

#define HAVE_QRENCODE 0

#define HAVE_QUOTACTL_FD 0

#define HAVE_REMOVEXATTRAT 0

#define HAVE_RENAMEAT2 1

#define HAVE_REQUEST_KEY 0

#define HAVE_RT_TGSIGQUEUEINFO 0

#define HAVE_SCHED_SETATTR 1

#define HAVE_SECCOMP 0

#define HAVE_SELINUX 0

#define HAVE_SETXATTRAT 0

#define HAVE_SET_MEMPOLICY 0

#define HAVE_SMACK_RUN_LABEL 0

/* bin and sbin directories are separate */
#define HAVE_SPLIT_BIN 1

#define HAVE_SYS_SDT_H 0

#define HAVE_THREADS_H 1

#define HAVE_TPM2 0

#define HAVE_TSS2_ESYS3 0

#define HAVE_VALGRIND_MEMCHECK_H 0

#define HAVE_VALGRIND_VALGRIND_H 0

#define HAVE_VMLINUX_H 0

#define HAVE_WARNING_ZERO_AS_NULL_POINTER_CONSTANT 1

#define HAVE_WARNING_ZERO_LENGTH_BOUNDS 0

#define HAVE_XENCTRL 0

#define HAVE_XKBCOMMON 0

#define HAVE_XZ 0

#define HAVE_ZLIB 0

#define HAVE_ZSTD 0

#define HIGH_RLIMIT_NOFILE 524288

#define INCLUDE_DIR "/usr/include"

#define INPUT_GID -

#define JOURNAL_STORAGE_DEFAULT persistent

#define JOURNAL_STORAGE_DEFAULT_VAL STORAGE_PERSISTENT

#define KBD_LOADKEYS "/usr/bin/loadkeys"

#define KBD_SETFONT "/usr/bin/setfont"

#define KERNEL_INSTALL_DIR "/usr/lib/kernel/install.d"

#define KEXEC "/usr/sbin/kexec"

#define KILL_USER_PROCESSES 1

#define KMEM_GID -

#define KMOD "/usr/bin/kmod"

#define KVM_GID -

#define LIBDIR "/usr/lib"

#define LIBEXECDIR "/usr/lib/systemd"

#define LINK_OSC_CONTEXT_DROPIN 1

#define LINK_SHELL_EXTRA_DROPIN 1

#define LINK_SSHD_USERDB_DROPIN 1

#define LINK_SSH_PROXY_DROPIN 1

#define LOG_MESSAGE_VERIFICATION 1

#define LOG_TRACE 0

#define LONG_MAX_STR "9223372036854775807"

#define LP_GID -

#define MEMORY_ACCOUNTING_DEFAULT 1

#define MODPROBE_DIR "/usr/lib/modprobe.d"

#define MODULESLOAD_DIR "/usr/lib/modules-load.d"

#define MOUNT_PATH "/usr/bin/mount"

#define NOBODY_GROUP_NAME "nobody"

#define NOBODY_USER_NAME "nobody"

#define NOLOGIN "/usr/sbin/nologin"

#define NTP_SERVERS "time1.google.com time2.google.com time3.google.com time4.google.com"

#define PKGSYSCONFDIR "/etc/systemd"

#define POLKIT_RULES_DIR "/usr/share/polkit-1/rules.d"

#define PREFIX "/usr/lib/systemd"

#define PREFIX_NOSLASH "/usr/lib/systemd"

#define PROJECT_URL "https://systemd.io/"

/* Numerical project version (used where a simple number is expected) */
#define PROJECT_VERSION 260

/* Full project version */
#define PROJECT_VERSION_FULL "260.1"

/* Stringified project version (used where a simple string is expected) */
#define PROJECT_VERSION_STR "260"

#define QUOTACHECK "/usr/sbin/quotacheck"

#define QUOTAON "/usr/sbin/quotaon"

#define RANDOM_SEED "/var/lib/systemd/random-seed"

#define RANDOM_SEED_DIR "/var/lib/systemd"

#define RELATIVE_SOURCE_PATH "."

#define RENDER_GID -

#define SD_BOOT 0

#define SERVICE_WATCHDOG "WatchdogSec=3min"

#define SGX_GID -

#define SHELLPROFILEDIR "/etc/profile.d"

#define SIZEOF_DEV_T 8

#define SIZEOF_INO_T 8

#define SIZEOF_RLIM_T 8

#define SIZEOF_TIMEX_MEMBER 8

#define SIZEOF_TIME_T 8

#define SSHCONFDIR "/etc/ssh/ssh_config.d"

#define SSHDCONFDIR "/etc/ssh/sshd_config.d"

/* SSH privilege separation directory */
#define SSHDPRIVSEPDIR /run/sshd

#define STATUS_UNIT_FORMAT_DEFAULT STATUS_UNIT_FORMAT_NAME

#define STATUS_UNIT_FORMAT_DEFAULT_STR "name"

#define SULOGIN "/usr/sbin/sulogin"

#define SUSHELL "/bin/sh"

#define SWAPOFF "/usr/sbin/swapoff"

#define SWAPON "/usr/sbin/swapon"

#define SYSCONF_DIR "/etc"

#define SYSCTL_DIR "/usr/lib/sysctl.d"

#define SYSTEMCTL_BINARY_PATH "/usr/bin/systemctl"

#define SYSTEMD_BINARY_PATH "/usr/lib/systemd/systemd"

#define SYSTEMD_CATALOG_DIR "/usr/lib/systemd/catalog"

#define SYSTEMD_CRYPTSETUP_PATH "/usr/bin/systemd-cryptsetup"

#define SYSTEMD_DEFAULT_KEYMAP "us"

#define SYSTEMD_DEFAULT_LOCALE "C.UTF-8"

#define SYSTEMD_EXECUTOR_BINARY_PATH "/usr/lib/systemd/systemd-executor"

#define SYSTEMD_EXPORT_PATH "/usr/lib/systemd/systemd-export"

#define SYSTEMD_FSCK_PATH "/usr/lib/systemd/systemd-fsck"

#define SYSTEMD_GROWFS_PATH "/usr/lib/systemd/systemd-growfs"

#define SYSTEMD_HOMEWORK_PATH "/usr/lib/systemd/systemd-homework"

#define SYSTEMD_IMPORT_FS_PATH "/usr/lib/systemd/systemd-import-fs"

#define SYSTEMD_IMPORT_PATH "/usr/lib/systemd/systemd-import"

#define SYSTEMD_INTEGRITYSETUP_PATH "/usr/lib/systemd/systemd-integritysetup"

#define SYSTEMD_JOURNAL_GID -

#define SYSTEMD_KBD_MODEL_MAP "/usr/share/systemd/kbd-model-map"

#define SYSTEMD_LANGUAGE_FALLBACK_MAP "/usr/share/systemd/language-fallback-map"

#define SYSTEMD_MAKEFS_PATH "/usr/lib/systemd/systemd-makefs"

#define SYSTEMD_MOUNTWORK_PATH "/usr/lib/systemd/systemd-mountwork"

#define SYSTEMD_NETWORK_UID -

#define SYSTEMD_NSPAWN_LOCALE "C.UTF-8"

#define SYSTEMD_NSRESOURCEWORK_PATH "/usr/lib/systemd/systemd-nsresourcework"

#define SYSTEMD_PULL_PATH "/usr/lib/systemd/systemd-pull"

#define SYSTEMD_RESOLVE_UID -

#define SYSTEMD_SHUTDOWN_BINARY_PATH "/usr/lib/systemd/systemd-shutdown"

#define SYSTEMD_SLOW_TESTS_DEFAULT 0

#define SYSTEMD_SYSUPDATE_PATH "/usr/lib/systemd/systemd-sysupdate"

#define SYSTEMD_TEST_DATA "/usr/lib/systemd/tests/testdata"

#define SYSTEMD_TIMESYNC_UID -

#define SYSTEMD_TTY_ASK_PASSWORD_AGENT_BINARY_PATH "/usr/bin/systemd-tty-ask-password-agent"

#define SYSTEMD_UPDATE_HELPER_PATH "/usr/lib/systemd/systemd-update-helper"

#define SYSTEMD_USERWORK_PATH "/usr/lib/systemd/systemd-userwork"

#define SYSTEMD_VERITYSETUP_PATH "/usr/lib/systemd/systemd-veritysetup"

#define SYSTEM_ALLOC_GID_MIN 1

#define SYSTEM_ALLOC_UID_MIN 1

#define SYSTEM_CONFIG_UNIT_DIR "/etc/systemd/system"

#define SYSTEM_DATA_UNIT_DIR "/usr/lib/systemd/system"

#define SYSTEM_ENV_GENERATOR_DIR "/usr/lib/systemd/system-environment-generators"

#define SYSTEM_GENERATOR_DIR "/usr/lib/systemd/system-generators"

#define SYSTEM_GID_MAX 999

#define SYSTEM_PRESET_DIR "/usr/lib/systemd/system-preset"

#define SYSTEM_SHUTDOWN_PATH "/usr/lib/systemd/system-shutdown"

#define SYSTEM_SLEEP_PATH "/usr/lib/systemd/system-sleep"

#define SYSTEM_UID_MAX 999

#define SYSUSERS_DIR "/usr/lib/sysusers.d"

#define TAPE_GID -

#define TIME_EPOCH 1777503534

#define TMPFILES_DIR "/usr/lib/tmpfiles.d"

#define TPM2_NVPCR_BASE 30474752

#define TTY_GID 5

#define TTY_MODE 0600

#define UDEVLIBEXECDIR "/usr/lib/udev"

#define UDEV_HWDB_DIR "/usr/lib/udev/hwdb.d"

#define UDEV_RULES_DIR "/usr/lib/udev/rules.d"

#define UMOUNT_PATH "/usr/bin/umount"

#define UPDATE_HELPER_USER_TIMEOUT_SEC 15

#define USERS_GID -

#define USER_CONFIG_UNIT_DIR "/etc/systemd/user"

#define USER_DATA_UNIT_DIR "/usr/lib/systemd/user"

#define USER_ENV_GENERATOR_DIR "/usr/lib/systemd/user-environment-generators"

#define USER_GENERATOR_DIR "/usr/lib/systemd/user-generators"

#define USER_KEYRING_PATH "/etc/systemd/import-pubring.pgp"

#define USER_KEYRING_PATH_LEGACY "/etc/systemd/import-pubring.gpg"

#define USER_PRESET_DIR "/usr/lib/systemd/user-preset"

#define USER_TMPFILES_DIR "/usr/share/user-tmpfiles.d"

#define UTMP_GID -

#define VARLINK_BRIDGES_DIR "/usr/lib/systemd/varlink-bridges"

#define VENDOR_KEYRING_PATH "/usr/lib/systemd/import-pubring.pgp"

#define VERSION_TAG "260.1"

#define VIDEO_GID -

#define WHEEL_GID -

#define _GNU_SOURCE 1

#define _LARGEFILE64_SOURCE 1

#define __SANE_USERSPACE_TYPES__

