#ifndef CPPUNIT_CONFIG_AUTO_H
#define CPPUNIT_CONFIG_AUTO_H

#define HAVE_CMATH 1
#define HAVE_CXX11 1
#define HAVE_DLERROR 1
#define HAVE_DLFCN_H 1
#define HAVE_NAMESPACES 1
#define HAVE_SSTREAM 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1
#define STDC_HEADERS 1

#define CPPUNIT_HAVE_NAMESPACES 1
#define CPPUNIT_HAVE_SSTREAM 1
#define CPPUNIT_HAVE_CPP_CAST 1

#endif // CPPUNIT_CONFIG_AUTO_H
