// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/timer/fdt_timer_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/timer/fdt_timer.h>

extern const struct fdt_driver fdt_timer_mtimer;
extern const struct fdt_driver fdt_timer_plmt;

const struct fdt_driver *const fdt_timer_drivers[] = {
	&fdt_timer_mtimer,
	&fdt_timer_plmt,
	NULL
};
