#!/usr/bin/env bash
#
#  bootstrap.bash - build the NVC standard libraries with the nvc compiler.
#
#  The VHDL standard libraries (STD, IEEE, NVC, ...) are produced by running
#  the freshly built nvc binary over the library sources, exactly as the
#  autotools `make bootstrap` target does.  Each design unit must be analysed
#  after the units it depends on, and the dependency graph is already captured
#  in the checked-in lib/*/deps.mk files (generated by `nvc --print-deps`).
#
#  We parse those makefiles, topologically sort the analysis units with
#  tsort(1), and invoke nvc once per source file in the resulting order.  The
#  whole library tree is written below $OUT, with one sub-directory per library
#  (std, std.08, ieee, nvc.19, ...) so that nvc's standard-suffix resolution
#  finds the right variant for each --std.
#
#  Usage:
#    bootstrap.bash <nvc> <out_dir> <deps.mk>...
#
set -euo pipefail

if [ "$#" -lt 3 ]; then
   echo "usage: bootstrap.bash <nvc> <out_dir> <deps.mk>..." >&2
   exit 2
fi

NVC="$1"; shift
OUT="$1"; shift
# Remaining arguments are the deps.mk files.

# The library .vhd sources live next to the deps.mk manifests.  When nvc is the
# main repository these paths are "lib/<dir>/deps.mk"; when nvc is consumed as
# an external repository (e.g. via the Bazel Central Registry) they are
# "external/<repo>/lib/<dir>/deps.mk".  Derive the prefix up to "lib/" so the
# sources are located correctly in both cases.
prefix="${1%lib/*}"
SRC="$PWD/$prefix"

# Make the compiler and output paths absolute (relative to the execroot); the
# source files are passed to nvc as absolute paths so that --relative can strip
# the prefix and store reproducible, relocatable paths in the libraries.
case "$NVC" in /*) ;; *) NVC="$PWD/$NVC" ;; esac
case "$OUT" in /*) ;; *) OUT="$PWD/$OUT" ;; esac

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

cat "$@" > "$work/all.deps"

# Pass 1: parse the dependency makefiles.
#
#   * Each target line looks like:
#       lib/<dir>/<UNIT>: $(top_srcdir)/lib/<...>.vhd  <unit deps...>
#   * The work unit is keyed by (library directory, source file) so that a
#     package and its body sharing one source file are analysed only once, and
#     so that a source compiled into several libraries (e.g. the Synopsys
#     packages) is analysed once per library.
#
# Outputs:
#   TABLE  id|workdir|source      (one row per work unit)
#   EDGES  "<dep id> <unit id>"   (topological-sort edges)
#   NODES  id                     (every work unit id)
awk -v out="$work" '
   function dirname(p) { sub(/\/[^/]*$/, "", p); return p }
   {
      ci = index($0, ":")
      if (ci == 0) next
      target = substr($0, 1, ci - 1)
      gsub(/^[ \t]+|[ \t]+$/, "", target)
      if (target !~ /^lib\//) next

      rest = substr($0, ci + 1)
      n = split(rest, a, /[ \t]+/)

      src = ""; si = 0
      for (i = 1; i <= n; i++) if (a[i] != "") { src = a[i]; si = i; break }
      if (src == "") next
      sub(/\$\(top_srcdir\)\//, "", src)

      wd = dirname(target)
      key = wd SUBSEP src
      if (!(key in id)) { id[key] = ++cnt; tdir[cnt] = wd; tsrc[cnt] = src }
      myid = id[key]
      u2i[target] = myid

      for (i = si + 1; i <= n; i++)
         if (a[i] != "") deps[myid] = deps[myid] " " a[i]
   }
   END {
      for (w = 1; w <= cnt; w++) {
         print w "|" tdir[w] "|" tsrc[w] > (out "/TABLE")
         print w > (out "/NODES")
         m = split(deps[w], d, " ")
         for (j = 1; j <= m; j++) if (d[j] != "") {
            dw = u2i[d[j]]
            if (dw != "" && dw != w) print dw " " w > (out "/EDGES")
         }
      }
   }
' "$work/all.deps"

touch "$work/EDGES"

# Topologically sort; tsort omits isolated nodes, so concatenate every node id
# afterwards and keep the first occurrence of each.
{ tsort "$work/EDGES" 2>/dev/null || true; cat "$work/NODES"; } \
   | awk '!seen[$0]++' > "$work/order"

declare -A WD SRCF
while IFS='|' read -r i d s; do
   WD[$i]="$d"
   SRCF[$i]="$s"
done < "$work/TABLE"

while read -r i; do
   [ -n "$i" ] || continue
   d="${WD[$i]}"
   s="${SRCF[$i]}"
   comp="${d#lib/}"                 # std, std.08, ieee, nvc.19, ...

   case "$comp" in
      *.08) std=2008 ;;
      *.19) std=2019 ;;
      *)    std=1993 ;;
   esac

   extra=()
   case "$s" in
      */standard.vhd)        extra+=(--bootstrap) ;;
   esac
   case "$s" in
      */vital/prmtvs_b.vhdl) extra+=(--relaxed) ;;
   esac

   mkdir -p "$OUT/$comp"
   "$NVC" --std="$std" -L "$OUT" --work="$OUT/$comp" -a \
      --relative="$SRC" "${extra[@]}" "$SRC/$s"
done < "$work/order"
