"""SDL2 autoconf checks used to generate SDL_config.h from the upstream template."""

load("@rules_cc_autoconf//autoconf:checks.bzl", "checks")

SDL2_CONFIG_CHECKS_COMMON = [
    checks.AC_CHECK_SIZEOF("void *", define = "SIZEOF_VOIDP"),
    checks.AC_DEFINE("HAVE_LIBC", "1"),
    checks.AC_DEFINE("STDC_HEADERS", "1"),
    checks.AC_DEFINE("HAVE_SETJMP", "1"),
    checks.AC_CHECK_HEADER("alloca.h", define = "HAVE_ALLOCA_H"),
    checks.AC_CHECK_HEADER("ctype.h", define = "HAVE_CTYPE_H"),
    checks.AC_CHECK_HEADER("float.h", define = "HAVE_FLOAT_H"),
    checks.AC_CHECK_HEADER("iconv.h", define = "HAVE_ICONV_H"),
    checks.AC_CHECK_HEADER("inttypes.h", define = "HAVE_INTTYPES_H"),
    checks.AC_CHECK_HEADER("limits.h", define = "HAVE_LIMITS_H"),
    checks.AC_CHECK_HEADER("malloc.h", define = "HAVE_MALLOC_H"),
    checks.AC_CHECK_HEADER("memory.h", define = "HAVE_MEMORY_H"),
    checks.AC_CHECK_HEADER("signal.h", define = "HAVE_SIGNAL_H"),
    checks.AC_CHECK_HEADER("stdint.h", define = "HAVE_STDINT_H"),
    checks.AC_CHECK_HEADER("stdio.h", define = "HAVE_STDIO_H"),
    checks.AC_CHECK_HEADER("stdlib.h", define = "HAVE_STDLIB_H"),
    checks.AC_CHECK_HEADER("string.h", define = "HAVE_STRING_H"),
    checks.AC_CHECK_HEADER("strings.h", define = "HAVE_STRINGS_H"),
    checks.AC_CHECK_HEADER("sys/types.h", define = "HAVE_SYS_TYPES_H"),
    checks.AC_CHECK_HEADER("wchar.h", define = "HAVE_WCHAR_H"),
    checks.AC_CHECK_HEADER("math.h", define = "HAVE_MATH_H"),
    checks.AC_CHECK_FUNC("abs", define = "HAVE_ABS"),
    checks.AC_CHECK_FUNC("alloca", define = "HAVE_ALLOCA"),
    checks.AC_CHECK_FUNC("atof", define = "HAVE_ATOF"),
    checks.AC_CHECK_FUNC("atoi", define = "HAVE_ATOI"),
    checks.AC_CHECK_FUNC("calloc", define = "HAVE_CALLOC"),
    checks.AC_CHECK_FUNC("free", define = "HAVE_FREE"),
    checks.AC_CHECK_FUNC("getenv", define = "HAVE_GETENV"),
    checks.AC_CHECK_FUNC("malloc", define = "HAVE_MALLOC"),
    checks.AC_CHECK_FUNC("memcmp", define = "HAVE_MEMCMP"),
    checks.AC_CHECK_FUNC("memcpy", define = "HAVE_MEMCPY"),
    checks.AC_CHECK_FUNC("memmove", define = "HAVE_MEMMOVE"),
    checks.AC_CHECK_FUNC("memset", define = "HAVE_MEMSET"),
    checks.AC_CHECK_FUNC("realloc", define = "HAVE_REALLOC"),
    checks.AC_CHECK_FUNC("strlen", define = "HAVE_STRLEN"),
    checks.AC_CHECK_FUNC("strtoll", define = "HAVE_STRTOLL"),
    checks.AC_CHECK_FUNC("strtoull", define = "HAVE_STRTOULL"),
    checks.AC_CHECK_FUNC("vsscanf", define = "HAVE_VSSCANF"),
    checks.AC_CHECK_FUNC("poll", define = "HAVE_POLL"),
    checks.AC_CHECK_FUNC("mprotect", define = "HAVE_MPROTECT"),
    checks.AC_CHECK_FUNC("nanosleep", define = "HAVE_NANOSLEEP"),
    checks.AC_CHECK_FUNC("clock_gettime", define = "HAVE_CLOCK_GETTIME"),
]

SDL2_CONFIG_CHECKS_NON_WINDOWS = SDL2_CONFIG_CHECKS_COMMON + [
    checks.AC_DEFINE("HAVE_GCC_ATOMICS", "1"),
    checks.AC_DEFINE("HAVE_DLOPEN", "1"),
    checks.AC_DEFINE("SDL_LOADSO_DLOPEN", "1"),
    checks.AC_DEFINE("SDL_THREAD_PTHREAD", "1"),
    checks.AC_DEFINE("SDL_THREAD_PTHREAD_RECURSIVE_MUTEX", "1"),
    checks.AC_DEFINE("SDL_TIMER_UNIX", "1"),
    checks.AC_DEFINE("SDL_FILESYSTEM_UNIX", "1"),
    checks.AC_DEFINE("DYNAPI_NEEDS_DLOPEN", "1"),
]

SDL2_CONFIG_CHECKS_LINUX = SDL2_CONFIG_CHECKS_NON_WINDOWS + [
    checks.AC_CHECK_HEADER("linux/input.h", define = "HAVE_LINUX_INPUT_H"),
    checks.AC_DEFINE("HAVE_O_CLOEXEC", "1"),
    # Audio
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_DISK", "1"),
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_DUMMY", "1"),
    # Input
    checks.AC_DEFINE("SDL_INPUT_LINUXEV", condition = "HAVE_LINUX_INPUT_H", if_true = "1"),
    checks.AC_DEFINE("SDL_INPUT_LINUXKD", condition = "HAVE_LINUX_INPUT_H", if_true = "1"),
    checks.AC_DEFINE("SDL_JOYSTICK_LINUX", condition = "HAVE_LINUX_INPUT_H", if_true = "1"),
    checks.AC_DEFINE("SDL_HAPTIC_LINUX", condition = "HAVE_LINUX_INPUT_H", if_true = "1"),
    # Video
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_X11", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_X11_SUPPORTS_GENERIC_EVENTS", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_X11_XCURSOR", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_X11_XINPUT2", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_X11_XFIXES", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_X11_XRANDR", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_X11_XSHAPE", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_DUMMY", "1"),
    checks.AC_DEFINE("SDL_VIDEO_RENDER_OGL_ES2", "1"),
    checks.AC_DEFINE("SDL_VIDEO_OPENGL_ES2", "1"),
    checks.AC_DEFINE("SDL_POWER_LINUX", "1"),
    checks.AC_DEFINE("SDL_SENSOR_DUMMY", "1"),
]

SDL2_CONFIG_CHECKS_LINUX_OPENGL = [
    checks.AC_DEFINE("SDL_VIDEO_RENDER_OGL", "1"),
    checks.AC_DEFINE("SDL_VIDEO_OPENGL", "1"),
    checks.AC_DEFINE("SDL_VIDEO_OPENGL_EGL", "1"),
    checks.AC_DEFINE("SDL_VIDEO_OPENGL_GLX", "1"),
]

SDL2_CONFIG_CHECKS_MACOS = SDL2_CONFIG_CHECKS_NON_WINDOWS + [
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_COREAUDIO", "1"),
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_DISK", "1"),
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_DUMMY", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_COCOA", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_DUMMY", "1"),
    checks.AC_DEFINE("SDL_VIDEO_OPENGL_CGL", "1"),
    checks.AC_DEFINE("SDL_VIDEO_RENDER_METAL", "1"),
    checks.AC_DEFINE("SDL_VIDEO_METAL", "1"),
    checks.AC_DEFINE("SDL_VIDEO_VULKAN", "1"),
    checks.AC_DEFINE("SDL_JOYSTICK_IOKIT", "1"),
    checks.AC_DEFINE("SDL_JOYSTICK_HIDAPI", "1"),
    checks.AC_DEFINE("SDL_JOYSTICK_MFI", "1"),
    checks.AC_DEFINE("SDL_JOYSTICK_VIRTUAL", "1"),
    checks.AC_DEFINE("SDL_HAPTIC_IOKIT", "1"),
    checks.AC_DEFINE("SDL_POWER_MACOSX", "1"),
    checks.AC_DEFINE("SDL_FILESYSTEM_COCOA", "1"),
    checks.AC_DEFINE("SDL_SENSOR_DUMMY", "1"),
]

SDL2_CONFIG_CHECKS_WINDOWS = SDL2_CONFIG_CHECKS_COMMON + [
    checks.AC_CHECK_HEADER("ddraw.h", define = "HAVE_DDRAW_H"),
    checks.AC_CHECK_HEADER("dsound.h", define = "HAVE_DSOUND_H"),
    checks.AC_CHECK_HEADER("dinput.h", define = "HAVE_DINPUT_H"),
    checks.AC_CHECK_HEADER("dxgi.h", define = "HAVE_DXGI_H"),
    checks.AC_CHECK_HEADER("mmdeviceapi.h", define = "HAVE_MMDEVICEAPI_H"),
    checks.AC_CHECK_HEADER("audioclient.h", define = "HAVE_AUDIOCLIENT_H"),
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_WASAPI", "1"),
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_DSOUND", "1"),
    checks.AC_DEFINE("SDL_AUDIO_DRIVER_WINMM", "1"),
    checks.AC_DEFINE("SDL_VIDEO_DRIVER_WINDOWS", "1"),
    checks.AC_DEFINE("SDL_JOYSTICK_DINPUT", "1"),
    checks.AC_DEFINE("SDL_JOYSTICK_XINPUT", "1"),
    checks.AC_DEFINE("SDL_HAPTIC_DINPUT", "1"),
    checks.AC_DEFINE("SDL_LOADSO_WINDOWS", "1"),
    checks.AC_DEFINE("SDL_THREAD_WINDOWS", "1"),
    checks.AC_DEFINE("SDL_TIMER_WINDOWS", "1"),
    checks.AC_DEFINE("SDL_POWER_WINDOWS", "1"),
    checks.AC_DEFINE("SDL_FILESYSTEM_WINDOWS", "1"),
    checks.AC_DEFINE("SDL_SENSOR_WINDOWS", "1"),
    checks.AC_DEFINE("SDL_SENSOR_DUMMY", "1"),
]
