// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/cppc/fdt_cppc_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/cppc/fdt_cppc.h>

extern const struct fdt_driver fdt_cppc_rpmi;

const struct fdt_driver *const fdt_cppc_drivers[] = {
	&fdt_cppc_rpmi,
	NULL
};
