// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/mpxy/fdt_mpxy_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/mpxy/fdt_mpxy.h>

extern const struct fdt_driver fdt_mpxy_rpmi_mbox;

const struct fdt_driver *const fdt_mpxy_drivers[] = {
	&fdt_mpxy_rpmi_mbox,
	NULL
};
