"""The gas configuration of binutils 2.47, per platform of //:targets.bzl.

GENERATED by modules/binutils/generate_targets.py; do not edit.  Results
identical between platforms are shared, named after the first platform using them.
"""

visibility(["//..."])

_GAS_LINUX_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": True,
        "x86_used_note": True,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-pc-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-pc-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_LINUX_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": True,
        "x86_used_note": True,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-pc-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-pc-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_LINUX_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-unknown-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-unknown-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_AARCH32 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"arm-unknown-linux-gnueabi\\\"\"",
        "TARGET_CANONICAL=\"\\\"arm-unknown-linux-gnueabi\\\"\"",
        "TARGET_CPU=\"\\\"arm\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnueabi\\\"\"",
    ],
    "em": "armlinuxeabi",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_ARMV7 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"armv7-unknown-linux-gnueabihf\\\"\"",
        "TARGET_CANONICAL=\"\\\"armv7-unknown-linux-gnueabihf\\\"\"",
        "TARGET_CPU=\"\\\"armv7\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnueabihf\\\"\"",
    ],
    "em": "armlinuxeabi",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_PPC = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc64-unknown-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc64-unknown-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"powerpc64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_PPC32 = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc-unknown-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc-unknown-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"powerpc\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_PPC64LE = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc64le-unknown-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc64le-unknown-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"powerpc64le\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_S390X = {
    "cpu_type": "s390",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"s390x\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"s390x-ibm-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"s390x-ibm-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"s390x\\\"\"",
        "TARGET_VENDOR=\"\\\"ibm\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-s390.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_MIPS64 = {
    "cpu_type": "mips",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "MIPS_CPU_STRING_DEFAULT=\"\\\"from-abi\\\"\"",
        "USE_EF_MIPS_ABI_O32=1",
        "MIPS_DEFAULT_64BIT=1",
        "MIPS_DEFAULT_ABI=N64_ABI",
        "USE_EMULATIONS=1",
        "EMULATIONS=\"&mipsbelf, &mipslelf, &mipself,\"",
        "DEFAULT_EMULATION=\"\\\"mipsbelf\\\"\"",
        "TARGET_ALIAS=\"\\\"mips64-unknown-linux-gnuabi64\\\"\"",
        "TARGET_CANONICAL=\"\\\"mips64-unknown-linux-gnuabi64\\\"\"",
        "TARGET_CPU=\"\\\"mips64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnuabi64\\\"\"",
    ],
    "em": "tmips",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-mips.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
        "itbl-parse.c",
        "itbl-lex-wrapper.c",
        "itbl-ops.c",
        "config/e-mipself.c",
    ],
}

_GAS_LINUX_RISCV32 = {
    "cpu_type": "riscv",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"riscv32\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"riscv32-unknown-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"riscv32-unknown-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"riscv32\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": True,
    "srcs": [
        "config/tc-riscv.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_LINUX_RISCV64 = {
    "cpu_type": "riscv",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"riscv64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"riscv64-unknown-linux-gnu\\\"\"",
        "TARGET_CANONICAL=\"\\\"riscv64-unknown-linux-gnu\\\"\"",
        "TARGET_CPU=\"\\\"riscv64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-gnu\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": True,
    "srcs": [
        "config/tc-riscv.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_ANDROID_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": True,
        "x86_used_note": True,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-pc-linux-android\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-pc-linux-android\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"linux-android\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_ANDROID_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": True,
        "x86_used_note": True,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-pc-linux-android\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-pc-linux-android\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"linux-android\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_ANDROID_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-unknown-linux-android\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-unknown-linux-android\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-android\\\"\"",
    ],
    "em": "linux",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_ANDROID_AARCH32 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"arm-unknown-linux-androideabi\\\"\"",
        "TARGET_CANONICAL=\"\\\"arm-unknown-linux-androideabi\\\"\"",
        "TARGET_CPU=\"\\\"arm\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-androideabi\\\"\"",
    ],
    "em": "armlinuxeabi",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_ANDROID_ARMV7 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"armv7-unknown-linux-androideabi\\\"\"",
        "TARGET_CANONICAL=\"\\\"armv7-unknown-linux-androideabi\\\"\"",
        "TARGET_CPU=\"\\\"armv7\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-androideabi\\\"\"",
    ],
    "em": "armlinuxeabi",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_ANDROID_RISCV64 = {
    "cpu_type": "riscv",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"riscv64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"riscv64-unknown-linux-android\\\"\"",
        "TARGET_CANONICAL=\"\\\"riscv64-unknown-linux-android\\\"\"",
        "TARGET_CPU=\"\\\"riscv64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"linux-android\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": True,
    "srcs": [
        "config/tc-riscv.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_WINDOWS_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "I386COFF=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-w64-mingw32\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-w64-mingw32\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"w64\\\"\"",
        "TARGET_OS=\"\\\"mingw32\\\"\"",
    ],
    "em": "pep",
    "obj_format": "coff",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-coff.c",
        "config/atof-ieee.c",
    ],
}

_GAS_WINDOWS_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "I386COFF=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-w64-mingw32\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-w64-mingw32\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"w64\\\"\"",
        "TARGET_OS=\"\\\"mingw32\\\"\"",
    ],
    "em": "pe",
    "obj_format": "coff",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-coff.c",
        "config/atof-ieee.c",
    ],
}

_GAS_WINDOWS_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-w64-mingw32\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-w64-mingw32\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"w64\\\"\"",
        "TARGET_OS=\"\\\"mingw32\\\"\"",
    ],
    "em": "pepaarch64",
    "obj_format": "coff",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-coff.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FREEBSD_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-pc-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-pc-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "freebsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_FREEBSD_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-pc-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-pc-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "freebsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_FREEBSD_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "freebsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FREEBSD_AARCH32 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"arm-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"arm-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"arm\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "armfbsdeabi",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FREEBSD_ARMV7 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"armv7-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"armv7-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"armv7\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "armfbsdeabi",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FREEBSD_PPC = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc64-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc64-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"powerpc64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "freebsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FREEBSD_PPC32 = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"powerpc\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "freebsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FREEBSD_PPC64LE = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc64le-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc64le-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"powerpc64le\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "freebsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FREEBSD_MIPS64 = {
    "cpu_type": "mips",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "MIPS_CPU_STRING_DEFAULT=\"\\\"from-abi\\\"\"",
        "USE_EF_MIPS_ABI_O32=1",
        "MIPS_DEFAULT_64BIT=1",
        "MIPS_DEFAULT_ABI=N32_ABI",
        "USE_EMULATIONS=1",
        "EMULATIONS=\"&mipsbelf, &mipslelf, &mipself,\"",
        "DEFAULT_EMULATION=\"\\\"mipsbelf\\\"\"",
        "TARGET_ALIAS=\"\\\"mips64-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"mips64-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"mips64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "freebsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-mips.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
        "itbl-parse.c",
        "itbl-lex-wrapper.c",
        "itbl-ops.c",
        "config/e-mipself.c",
    ],
}

_GAS_FREEBSD_RISCV64 = {
    "cpu_type": "riscv",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"riscv64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"riscv64-unknown-freebsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"riscv64-unknown-freebsd\\\"\"",
        "TARGET_CPU=\"\\\"riscv64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"freebsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": True,
    "srcs": [
        "config/tc-riscv.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_NETBSD_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-pc-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-pc-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "nbsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_NETBSD_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-pc-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-pc-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "nbsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_NETBSD_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-unknown-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-unknown-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "nbsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_NETBSD_AARCH32 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"arm-unknown-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"arm-unknown-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"arm\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "nbsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_NETBSD_PPC = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc64-unknown-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc64-unknown-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"powerpc64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_NETBSD_PPC32 = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc-unknown-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc-unknown-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"powerpc\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_NETBSD_MIPS64 = {
    "cpu_type": "mips",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "MIPS_CPU_STRING_DEFAULT=\"\\\"from-abi\\\"\"",
        "USE_EF_MIPS_ABI_O32=1",
        "MIPS_DEFAULT_64BIT=1",
        "MIPS_DEFAULT_ABI=NO_ABI",
        "USE_EMULATIONS=1",
        "EMULATIONS=\"&mipsbelf, &mipslelf, &mipself,\"",
        "DEFAULT_EMULATION=\"\\\"mipsbelf\\\"\"",
        "TARGET_ALIAS=\"\\\"mips64-unknown-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"mips64-unknown-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"mips64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "tmips",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-mips.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
        "itbl-parse.c",
        "itbl-lex-wrapper.c",
        "itbl-ops.c",
        "config/e-mipself.c",
    ],
}

_GAS_NETBSD_RISCV64 = {
    "cpu_type": "riscv",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"riscv64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"riscv64-unknown-netbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"riscv64-unknown-netbsd\\\"\"",
        "TARGET_CPU=\"\\\"riscv64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"netbsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": True,
    "srcs": [
        "config/tc-riscv.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_OPENBSD_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-pc-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-pc-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "nbsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_OPENBSD_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-pc-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-pc-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "nbsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_OPENBSD_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-unknown-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-unknown-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_OPENBSD_AARCH32 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"arm-unknown-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"arm-unknown-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"arm\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "nbsd",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_OPENBSD_PPC = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc64-unknown-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc64-unknown-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"powerpc64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_OPENBSD_PPC32 = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc-unknown-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc-unknown-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"powerpc\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_OPENBSD_MIPS64 = {
    "cpu_type": "mips",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "MIPS_CPU_STRING_DEFAULT=\"\\\"from-abi\\\"\"",
        "USE_EF_MIPS_ABI_O32=1",
        "MIPS_DEFAULT_64BIT=1",
        "MIPS_DEFAULT_ABI=N64_ABI",
        "USE_EMULATIONS=1",
        "EMULATIONS=\"&mipsbelf, &mipslelf, &mipself,\"",
        "DEFAULT_EMULATION=\"\\\"mipsbelf\\\"\"",
        "TARGET_ALIAS=\"\\\"mips64-unknown-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"mips64-unknown-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"mips64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "tmips",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-mips.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
        "itbl-parse.c",
        "itbl-lex-wrapper.c",
        "itbl-ops.c",
        "config/e-mipself.c",
    ],
}

_GAS_OPENBSD_RISCV64 = {
    "cpu_type": "riscv",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"riscv64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"riscv64-unknown-openbsd\\\"\"",
        "TARGET_CANONICAL=\"\\\"riscv64-unknown-openbsd\\\"\"",
        "TARGET_CPU=\"\\\"riscv64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"openbsd\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": True,
    "srcs": [
        "config/tc-riscv.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_HAIKU_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-unknown-haiku\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-unknown-haiku\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"haiku\\\"\"",
    ],
    "em": "haiku",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_HAIKU_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-unknown-haiku\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-unknown-haiku\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"haiku\\\"\"",
    ],
    "em": "haiku",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_VXWORKS_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-wrs-vxworks\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-wrs-vxworks\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"wrs\\\"\"",
        "TARGET_OS=\"\\\"vxworks\\\"\"",
    ],
    "em": "vxworks",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_VXWORKS_AARCH32 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"arm-wrs-vxworks\\\"\"",
        "TARGET_CANONICAL=\"\\\"arm-wrs-vxworks\\\"\"",
        "TARGET_CPU=\"\\\"arm\\\"\"",
        "TARGET_VENDOR=\"\\\"wrs\\\"\"",
        "TARGET_OS=\"\\\"vxworks\\\"\"",
    ],
    "em": "vxworks",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_VXWORKS_PPC32 = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc-wrs-vxworks\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc-wrs-vxworks\\\"\"",
        "TARGET_CPU=\"\\\"powerpc\\\"\"",
        "TARGET_VENDOR=\"\\\"wrs\\\"\"",
        "TARGET_OS=\"\\\"vxworks\\\"\"",
    ],
    "em": "vxworks",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_VXWORKS_MIPS64 = {
    "cpu_type": "mips",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "MIPS_CPU_STRING_DEFAULT=\"\\\"from-abi\\\"\"",
        "USE_EF_MIPS_ABI_O32=1",
        "MIPS_DEFAULT_64BIT=1",
        "MIPS_DEFAULT_ABI=NO_ABI",
        "USE_EMULATIONS=1",
        "EMULATIONS=\"&mipsbelf, &mipslelf, &mipself,\"",
        "DEFAULT_EMULATION=\"\\\"mipsbelf\\\"\"",
        "TARGET_ALIAS=\"\\\"mips64-wrs-vxworks\\\"\"",
        "TARGET_CANONICAL=\"\\\"mips64-wrs-vxworks\\\"\"",
        "TARGET_CPU=\"\\\"mips64\\\"\"",
        "TARGET_VENDOR=\"\\\"wrs\\\"\"",
        "TARGET_OS=\"\\\"vxworks\\\"\"",
    ],
    "em": "vxworks",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-mips.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
        "itbl-parse.c",
        "itbl-lex-wrapper.c",
        "itbl-ops.c",
        "config/e-mipself.c",
    ],
}

_GAS_QNX_X86_32 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"i386\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"i686-pc-nto-qnx\\\"\"",
        "TARGET_CANONICAL=\"\\\"i686-pc-nto-qnx\\\"\"",
        "TARGET_CPU=\"\\\"i686\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"nto-qnx\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_QNX_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-pc-nto-qnx\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-pc-nto-qnx\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"nto-qnx\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_QNX_AARCH32 = {
    "cpu_type": "arm",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"arm-pc-nto-qnx\\\"\"",
        "TARGET_CANONICAL=\"\\\"arm-pc-nto-qnx\\\"\"",
        "TARGET_CPU=\"\\\"arm\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"nto-qnx\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-arm.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_QNX_PPC32 = {
    "cpu_type": "ppc",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=1",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"powerpc-pc-nto-qnx\\\"\"",
        "TARGET_CANONICAL=\"\\\"powerpc-pc-nto-qnx\\\"\"",
        "TARGET_CPU=\"\\\"powerpc\\\"\"",
        "TARGET_VENDOR=\"\\\"pc\\\"\"",
        "TARGET_OS=\"\\\"nto-qnx\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-ppc.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FUCHSIA_X86_64 = {
    "cpu_type": "i386",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "DEFAULT_ARCH=\"\\\"x86_64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"x86_64-unknown-fuchsia\\\"\"",
        "TARGET_CANONICAL=\"\\\"x86_64-unknown-fuchsia\\\"\"",
        "TARGET_CPU=\"\\\"x86_64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"fuchsia\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-i386.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
    ],
}

_GAS_FUCHSIA_AARCH64 = {
    "cpu_type": "aarch64",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"aarch64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"aarch64-unknown-fuchsia\\\"\"",
        "TARGET_CANONICAL=\"\\\"aarch64-unknown-fuchsia\\\"\"",
        "TARGET_CPU=\"\\\"aarch64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"fuchsia\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": False,
    "srcs": [
        "config/tc-aarch64.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

_GAS_FUCHSIA_RISCV64 = {
    "cpu_type": "riscv",
    "defaults": {
        "compress_debug": False,
        "x86_used_note": False,
    },
    "defines": [
        "TARGET_BYTES_BIG_ENDIAN=0",
        "DEFAULT_ARCH=\"\\\"riscv64\\\"\"",
        "EMULATIONS=\"\"",
        "DEFAULT_EMULATION=\"\\\"\\\"\"",
        "TARGET_ALIAS=\"\\\"riscv64-unknown-fuchsia\\\"\"",
        "TARGET_CANONICAL=\"\\\"riscv64-unknown-fuchsia\\\"\"",
        "TARGET_CPU=\"\\\"riscv64\\\"\"",
        "TARGET_VENDOR=\"\\\"unknown\\\"\"",
        "TARGET_OS=\"\\\"fuchsia\\\"\"",
    ],
    "em": "generic",
    "obj_format": "elf",
    "riscv": True,
    "srcs": [
        "config/tc-riscv.c",
        "config/obj-elf.c",
        "config/atof-ieee.c",
        "config/obj-elf-attr.c",
    ],
}

GAS = {
    "android_aarch32": _GAS_ANDROID_AARCH32,
    "android_aarch64": _GAS_ANDROID_AARCH64,
    "android_armv7": _GAS_ANDROID_ARMV7,
    "android_i386": _GAS_ANDROID_X86_32,
    "android_riscv64": _GAS_ANDROID_RISCV64,
    "android_x86_32": _GAS_ANDROID_X86_32,
    "android_x86_64": _GAS_ANDROID_X86_64,
    "chromiumos_aarch32": _GAS_LINUX_AARCH32,
    "chromiumos_aarch64": _GAS_LINUX_AARCH64,
    "chromiumos_armv7": _GAS_LINUX_ARMV7,
    "chromiumos_i386": _GAS_LINUX_X86_32,
    "chromiumos_x86_32": _GAS_LINUX_X86_32,
    "chromiumos_x86_64": _GAS_LINUX_X86_64,
    "freebsd_aarch32": _GAS_FREEBSD_AARCH32,
    "freebsd_aarch64": _GAS_FREEBSD_AARCH64,
    "freebsd_armv7": _GAS_FREEBSD_ARMV7,
    "freebsd_i386": _GAS_FREEBSD_X86_32,
    "freebsd_mips64": _GAS_FREEBSD_MIPS64,
    "freebsd_ppc": _GAS_FREEBSD_PPC,
    "freebsd_ppc32": _GAS_FREEBSD_PPC32,
    "freebsd_ppc64le": _GAS_FREEBSD_PPC64LE,
    "freebsd_riscv64": _GAS_FREEBSD_RISCV64,
    "freebsd_x86_32": _GAS_FREEBSD_X86_32,
    "freebsd_x86_64": _GAS_FREEBSD_X86_64,
    "fuchsia_aarch64": _GAS_FUCHSIA_AARCH64,
    "fuchsia_riscv64": _GAS_FUCHSIA_RISCV64,
    "fuchsia_x86_64": _GAS_FUCHSIA_X86_64,
    "haiku_i386": _GAS_HAIKU_X86_32,
    "haiku_x86_32": _GAS_HAIKU_X86_32,
    "haiku_x86_64": _GAS_HAIKU_X86_64,
    "linux_aarch32": _GAS_LINUX_AARCH32,
    "linux_aarch64": _GAS_LINUX_AARCH64,
    "linux_armv7": _GAS_LINUX_ARMV7,
    "linux_i386": _GAS_LINUX_X86_32,
    "linux_mips64": _GAS_LINUX_MIPS64,
    "linux_ppc": _GAS_LINUX_PPC,
    "linux_ppc32": _GAS_LINUX_PPC32,
    "linux_ppc64le": _GAS_LINUX_PPC64LE,
    "linux_riscv32": _GAS_LINUX_RISCV32,
    "linux_riscv64": _GAS_LINUX_RISCV64,
    "linux_s390x": _GAS_LINUX_S390X,
    "linux_x86_32": _GAS_LINUX_X86_32,
    "linux_x86_64": _GAS_LINUX_X86_64,
    "macos_aarch64": None,
    "macos_x86_64": None,
    "netbsd_aarch32": _GAS_NETBSD_AARCH32,
    "netbsd_aarch64": _GAS_NETBSD_AARCH64,
    "netbsd_armv7": _GAS_NETBSD_AARCH32,
    "netbsd_i386": _GAS_NETBSD_X86_32,
    "netbsd_mips64": _GAS_NETBSD_MIPS64,
    "netbsd_ppc": _GAS_NETBSD_PPC,
    "netbsd_ppc32": _GAS_NETBSD_PPC32,
    "netbsd_riscv64": _GAS_NETBSD_RISCV64,
    "netbsd_x86_32": _GAS_NETBSD_X86_32,
    "netbsd_x86_64": _GAS_NETBSD_X86_64,
    "nixos_aarch32": _GAS_LINUX_AARCH32,
    "nixos_aarch64": _GAS_LINUX_AARCH64,
    "nixos_armv7": _GAS_LINUX_ARMV7,
    "nixos_i386": _GAS_LINUX_X86_32,
    "nixos_mips64": _GAS_LINUX_MIPS64,
    "nixos_ppc": _GAS_LINUX_PPC,
    "nixos_ppc32": _GAS_LINUX_PPC32,
    "nixos_ppc64le": _GAS_LINUX_PPC64LE,
    "nixos_riscv32": _GAS_LINUX_RISCV32,
    "nixos_riscv64": _GAS_LINUX_RISCV64,
    "nixos_s390x": _GAS_LINUX_S390X,
    "nixos_x86_32": _GAS_LINUX_X86_32,
    "nixos_x86_64": _GAS_LINUX_X86_64,
    "openbsd_aarch32": _GAS_OPENBSD_AARCH32,
    "openbsd_aarch64": _GAS_OPENBSD_AARCH64,
    "openbsd_armv7": _GAS_OPENBSD_AARCH32,
    "openbsd_i386": _GAS_OPENBSD_X86_32,
    "openbsd_mips64": _GAS_OPENBSD_MIPS64,
    "openbsd_ppc": _GAS_OPENBSD_PPC,
    "openbsd_ppc32": _GAS_OPENBSD_PPC32,
    "openbsd_riscv64": _GAS_OPENBSD_RISCV64,
    "openbsd_x86_32": _GAS_OPENBSD_X86_32,
    "openbsd_x86_64": _GAS_OPENBSD_X86_64,
    "qnx_aarch32": _GAS_QNX_AARCH32,
    "qnx_aarch64": _GAS_QNX_AARCH64,
    "qnx_armv7": _GAS_QNX_AARCH32,
    "qnx_i386": _GAS_QNX_X86_32,
    "qnx_ppc32": _GAS_QNX_PPC32,
    "qnx_x86_32": _GAS_QNX_X86_32,
    "vxworks_aarch32": _GAS_VXWORKS_AARCH32,
    "vxworks_armv7": _GAS_VXWORKS_AARCH32,
    "vxworks_i386": _GAS_VXWORKS_X86_32,
    "vxworks_mips64": _GAS_VXWORKS_MIPS64,
    "vxworks_ppc32": _GAS_VXWORKS_PPC32,
    "vxworks_x86_32": _GAS_VXWORKS_X86_32,
    "windows_aarch64": _GAS_WINDOWS_AARCH64,
    "windows_i386": _GAS_WINDOWS_X86_32,
    "windows_x86_32": _GAS_WINDOWS_X86_32,
    "windows_x86_64": _GAS_WINDOWS_X86_64,
}
