load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_java",
    sha256 = "c999cdbb4e8414d49c4117bb73800cff95c438c15da075531ae004275ab23144",
    urls = ["https://github.com/bazelbuild/rules_java/releases/download/7.12.0/rules_java-7.12.0.tar.gz"],
)

http_archive(
    name = "rules_jvm_external",
    sha256 = "23fe83890a77ac1a3ee143e2306ec12da4a845285b14ea13cb0df1b1e23658fe",
    strip_prefix = "rules_jvm_external-4.3",
    urls = ["https://github.com/bazelbuild/rules_jvm_external/archive/refs/tags/4.3.tar.gz"],
)

load("@rules_jvm_external//:defs.bzl", "maven_install")
load("@rules_jvm_external//:specs.bzl", "maven")

maven_install(
    name = "px_deps",
    artifacts = [
        "org.antlr:antlr4:4.11.1",
        "com.google.jimfs:jimfs:1.2",
        "com.google.truth:truth:1.4.0",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)

maven_install(
    artifacts = [
        "aopalliance:aopalliance:1.0",
        "org.apache.santuario:xmlsec:2.2.0",
        maven.artifact(
            "biz.aQute",
            "bnd",
            "0.0.384",
            testonly = True,
        ),
        maven.artifact(
            "com.google.truth",
            "truth",
            "1.4.0",
            testonly = True,
        ),
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
