name: Module Wanted
description: Request that a module be added to the registry
title: "wanted: [github path of the module, e.g. bazelbuild/rules_foo]"
labels: ["module wanted"]
body:
  - type: markdown
    attributes:
      value: |
        The Central Registry is populated by community contributions.
        You can file an issue to indicate that you depend on a module which isn't available here.
        A volunteer may contribute that module, but there is no guarantee.
        You may want to send a PR yourself, or consider sponsoring the work.

  - type: input
    id: location
    attributes:
      label: Module location
      description: Where can we find the source code for the module
    validations:
      required: true

  - type: input
    id: issue-link
    attributes:
      label: Link to bzlmod issue in the module's repository
      description: In many cases, upstream work is needed, such as writing module extensions in a ruleset.

  - type: textarea
    id: details
    attributes:
      label: Any other context to provide?
      description: What do we need to know about the module?

  - type: checkboxes
    id: sponsor
    attributes:
      label: Fund our work
      description: I'd like someone to add this module right away!
      options:
        - label: Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)
