"""The opcodes configuration of binutils 2.47, per platform of //:targets.bzl.

GENERATED by modules/binutils/generate_targets.py; do not edit.  Results
identical between platforms are shared, named after the first platform using them.
"""

visibility(["//..."])

_OPCODES_LINUX_X86_64 = {
    "defines": [
        "ARCH_i386",
    ],
    "machines": [
        "i386-dis.c",
    ],
}

_OPCODES_LINUX_AARCH64 = {
    "defines": [
        "ARCH_aarch64",
        "ARCH_arm",
    ],
    "machines": [
        "aarch64-asm.c",
        "aarch64-dis.c",
        "aarch64-opc.c",
        "aarch64-asm-2.c",
        "aarch64-dis-2.c",
        "aarch64-opc-2.c",
        "arm-dis.c",
    ],
}

_OPCODES_LINUX_AARCH32 = {
    "defines": [
        "ARCH_arm",
    ],
    "machines": [
        "arm-dis.c",
    ],
}

_OPCODES_LINUX_PPC = {
    "defines": [
        "ARCH_rs6000",
        "ARCH_powerpc",
    ],
    "machines": [
        "ppc-dis.c",
        "ppc-opc.c",
    ],
}

_OPCODES_LINUX_S390X = {
    "defines": [
        "ARCH_s390",
    ],
    "machines": [
        "s390-dis.c",
        "s390-opc.c",
    ],
}

_OPCODES_LINUX_MIPS64 = {
    "defines": [
        "ARCH_mips",
        "HAVE_BFD_MIPS_ELF_GET_ABIFLAGS=1",
    ],
    "machines": [
        "mips-dis.c",
        "mips-opc.c",
        "mips16-opc.c",
        "micromips-opc.c",
    ],
}

_OPCODES_LINUX_RISCV32 = {
    "defines": [
        "ARCH_riscv",
    ],
    "machines": [
        "riscv-dis.c",
        "riscv-opc.c",
    ],
}

_OPCODES_MACOS_X86_64 = {
    "defines": [
        "ARCH_i386",
        "ARCH_powerpc",
        "ARCH_rs6000",
    ],
    "machines": [
        "i386-dis.c",
        "ppc-dis.c",
        "ppc-opc.c",
    ],
}

_OPCODES_MACOS_AARCH64 = {
    "defines": [
        "ARCH_aarch64",
        "ARCH_arm",
        "ARCH_i386",
        "ARCH_powerpc",
        "ARCH_rs6000",
    ],
    "machines": [
        "aarch64-asm.c",
        "aarch64-dis.c",
        "aarch64-opc.c",
        "aarch64-asm-2.c",
        "aarch64-dis-2.c",
        "aarch64-opc-2.c",
        "arm-dis.c",
        "i386-dis.c",
        "ppc-dis.c",
        "ppc-opc.c",
    ],
}

OPCODES = {
    "android_aarch32": _OPCODES_LINUX_AARCH32,
    "android_aarch64": _OPCODES_LINUX_AARCH64,
    "android_armv7": _OPCODES_LINUX_AARCH32,
    "android_i386": _OPCODES_LINUX_X86_64,
    "android_riscv64": _OPCODES_LINUX_RISCV32,
    "android_x86_32": _OPCODES_LINUX_X86_64,
    "android_x86_64": _OPCODES_LINUX_X86_64,
    "chromiumos_aarch32": _OPCODES_LINUX_AARCH32,
    "chromiumos_aarch64": _OPCODES_LINUX_AARCH64,
    "chromiumos_armv7": _OPCODES_LINUX_AARCH32,
    "chromiumos_i386": _OPCODES_LINUX_X86_64,
    "chromiumos_x86_32": _OPCODES_LINUX_X86_64,
    "chromiumos_x86_64": _OPCODES_LINUX_X86_64,
    "freebsd_aarch32": _OPCODES_LINUX_AARCH32,
    "freebsd_aarch64": _OPCODES_LINUX_AARCH64,
    "freebsd_armv7": _OPCODES_LINUX_AARCH32,
    "freebsd_i386": _OPCODES_LINUX_X86_64,
    "freebsd_mips64": _OPCODES_LINUX_MIPS64,
    "freebsd_ppc": _OPCODES_LINUX_PPC,
    "freebsd_ppc32": _OPCODES_LINUX_PPC,
    "freebsd_ppc64le": _OPCODES_LINUX_PPC,
    "freebsd_riscv64": _OPCODES_LINUX_RISCV32,
    "freebsd_x86_32": _OPCODES_LINUX_X86_64,
    "freebsd_x86_64": _OPCODES_LINUX_X86_64,
    "fuchsia_aarch64": _OPCODES_LINUX_AARCH64,
    "fuchsia_riscv64": _OPCODES_LINUX_RISCV32,
    "fuchsia_x86_64": _OPCODES_LINUX_X86_64,
    "haiku_i386": _OPCODES_LINUX_X86_64,
    "haiku_x86_32": _OPCODES_LINUX_X86_64,
    "haiku_x86_64": _OPCODES_LINUX_X86_64,
    "linux_aarch32": _OPCODES_LINUX_AARCH32,
    "linux_aarch64": _OPCODES_LINUX_AARCH64,
    "linux_armv7": _OPCODES_LINUX_AARCH32,
    "linux_i386": _OPCODES_LINUX_X86_64,
    "linux_mips64": _OPCODES_LINUX_MIPS64,
    "linux_ppc": _OPCODES_LINUX_PPC,
    "linux_ppc32": _OPCODES_LINUX_PPC,
    "linux_ppc64le": _OPCODES_LINUX_PPC,
    "linux_riscv32": _OPCODES_LINUX_RISCV32,
    "linux_riscv64": _OPCODES_LINUX_RISCV32,
    "linux_s390x": _OPCODES_LINUX_S390X,
    "linux_x86_32": _OPCODES_LINUX_X86_64,
    "linux_x86_64": _OPCODES_LINUX_X86_64,
    "macos_aarch64": _OPCODES_MACOS_AARCH64,
    "macos_x86_64": _OPCODES_MACOS_X86_64,
    "netbsd_aarch32": _OPCODES_LINUX_AARCH32,
    "netbsd_aarch64": _OPCODES_LINUX_AARCH64,
    "netbsd_armv7": _OPCODES_LINUX_AARCH32,
    "netbsd_i386": _OPCODES_LINUX_X86_64,
    "netbsd_mips64": _OPCODES_LINUX_MIPS64,
    "netbsd_ppc": _OPCODES_LINUX_PPC,
    "netbsd_ppc32": _OPCODES_LINUX_PPC,
    "netbsd_riscv64": _OPCODES_LINUX_RISCV32,
    "netbsd_x86_32": _OPCODES_LINUX_X86_64,
    "netbsd_x86_64": _OPCODES_LINUX_X86_64,
    "nixos_aarch32": _OPCODES_LINUX_AARCH32,
    "nixos_aarch64": _OPCODES_LINUX_AARCH64,
    "nixos_armv7": _OPCODES_LINUX_AARCH32,
    "nixos_i386": _OPCODES_LINUX_X86_64,
    "nixos_mips64": _OPCODES_LINUX_MIPS64,
    "nixos_ppc": _OPCODES_LINUX_PPC,
    "nixos_ppc32": _OPCODES_LINUX_PPC,
    "nixos_ppc64le": _OPCODES_LINUX_PPC,
    "nixos_riscv32": _OPCODES_LINUX_RISCV32,
    "nixos_riscv64": _OPCODES_LINUX_RISCV32,
    "nixos_s390x": _OPCODES_LINUX_S390X,
    "nixos_x86_32": _OPCODES_LINUX_X86_64,
    "nixos_x86_64": _OPCODES_LINUX_X86_64,
    "openbsd_aarch32": _OPCODES_LINUX_AARCH32,
    "openbsd_aarch64": _OPCODES_LINUX_AARCH64,
    "openbsd_armv7": _OPCODES_LINUX_AARCH32,
    "openbsd_i386": _OPCODES_LINUX_X86_64,
    "openbsd_mips64": _OPCODES_LINUX_MIPS64,
    "openbsd_ppc": _OPCODES_LINUX_PPC,
    "openbsd_ppc32": _OPCODES_LINUX_PPC,
    "openbsd_riscv64": _OPCODES_LINUX_RISCV32,
    "openbsd_x86_32": _OPCODES_LINUX_X86_64,
    "openbsd_x86_64": _OPCODES_LINUX_X86_64,
    "qnx_aarch32": _OPCODES_LINUX_AARCH32,
    "qnx_aarch64": _OPCODES_LINUX_AARCH64,
    "qnx_armv7": _OPCODES_LINUX_AARCH32,
    "qnx_i386": _OPCODES_LINUX_X86_64,
    "qnx_ppc32": _OPCODES_LINUX_PPC,
    "qnx_x86_32": _OPCODES_LINUX_X86_64,
    "vxworks_aarch32": _OPCODES_LINUX_AARCH32,
    "vxworks_armv7": _OPCODES_LINUX_AARCH32,
    "vxworks_i386": _OPCODES_LINUX_X86_64,
    "vxworks_mips64": _OPCODES_LINUX_MIPS64,
    "vxworks_ppc32": _OPCODES_LINUX_PPC,
    "vxworks_x86_32": _OPCODES_LINUX_X86_64,
    "windows_aarch64": _OPCODES_LINUX_AARCH64,
    "windows_i386": _OPCODES_LINUX_X86_64,
    "windows_x86_32": _OPCODES_LINUX_X86_64,
    "windows_x86_64": _OPCODES_LINUX_X86_64,
}
