// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/platform/generic/platform_override_modules.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <platform_override.h>

extern const struct platform_override thead_generic;
extern const struct platform_override starfive_jh7110;
extern const struct platform_override sophgo_sg2042;
extern const struct platform_override sifive_fu540;
extern const struct platform_override sifive_fu740;
extern const struct platform_override renesas_rzfive;
extern const struct platform_override andes_ae350;
extern const struct platform_override sun20i_d1;

const struct platform_override *const platform_override_modules[] = {
	&thead_generic,
	&starfive_jh7110,
	&sophgo_sg2042,
	&sifive_fu540,
	&sifive_fu740,
	&renesas_rzfive,
	&andes_ae350,
	&sun20i_d1,
	NULL
};
