// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/hsm/fdt_hsm_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/hsm/fdt_hsm.h>

extern const struct fdt_driver fdt_hsm_rpmi;

const struct fdt_driver *const fdt_hsm_drivers[] = {
	&fdt_hsm_rpmi,
	NULL
};
