"""OpenFHE module configuration extension."""

_CONFIG_ATTRS = {
    "has_int128": attr.bool(default = True, doc = "Enable 128-bit integer support"),
    "mathbackend": attr.int(default = 4, doc = "Math backend (options are 1, 2, 4)"),
}

def _config_repo_impl(rctx):
    """Repository rule that creates the config files."""
    # Convert string dict back to usable types
    has_int128 = rctx.attr.has_int128
    mathbackend = rctx.attr.mathbackend

    rctx.file("BUILD.bazel", 'exports_files(["config.bzl", "generate_header.sh"])')

    # Store config values in .bzl for BUILD files to use
    rctx.file("config.bzl", """
HAS_INT128 = {has_int128}
MATHBACKEND = {mathbackend}
HAS_INT128_STR = "{has_int128_str}"
""".format(
        has_int128 = has_int128,
        mathbackend = mathbackend,
        has_int128_str = "TRUE" if has_int128 else "FALSE",
    ))

    # Create shell script that generates the header
    rctx.file("generate_header.sh", """#!/bin/bash
cat > "$1" << 'HEADER_EOF'
// This file is normally generated by CMake; we generate it for bazel builds.

#ifndef __CMAKE_GENERATED_CONFIG_CORE_H__
#define __CMAKE_GENERATED_CONFIG_CORE_H__

#define WITH_BE{mathbackend}
#define WITH_OPENMP
#define CKKS_M_FACTOR 1
#define HAVE_INT128 {has_int128_str}
#define HAVE_INT64 TRUE
#define MATHBACKEND {mathbackend}
#define NATIVEINT 64

#endif // __CMAKE_GENERATED_CONFIG_CORE_H__
HEADER_EOF
""".format(
        mathbackend = mathbackend,
        has_int128_str = "TRUE" if has_int128 else "FALSE",
    ), executable = True)

# Define the repository rule
_config_repo = repository_rule(
    implementation = _config_repo_impl,
    attrs = _CONFIG_ATTRS,
)

def _openfhe_config_impl(ctx):
    """Generate configuration based on module settings."""

    config = None
    for mod in ctx.modules:
        for cfg in mod.tags.configure:
            config = cfg
            break
        if config:
            break

    if not config:
        config = struct(has_int128 = True, mathbackend = 2)

    _config_repo(
        name = "openfhe_config",
        has_int128 = config.has_int128,
        mathbackend = config.mathbackend,
    )


_configure_tag = tag_class(attrs = _CONFIG_ATTRS)
openfhe_config = module_extension(
    implementation = _openfhe_config_impl,
    tag_classes = {"configure": _configure_tag},
)
