// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/sbi/sbi_ecall_exts.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi/sbi_ecall.h>

extern struct sbi_ecall_extension ecall_time;
extern struct sbi_ecall_extension ecall_rfence;
extern struct sbi_ecall_extension ecall_ipi;
extern struct sbi_ecall_extension ecall_base;
extern struct sbi_ecall_extension ecall_hsm;
extern struct sbi_ecall_extension ecall_srst;
extern struct sbi_ecall_extension ecall_susp;
extern struct sbi_ecall_extension ecall_pmu;
extern struct sbi_ecall_extension ecall_dbcn;
extern struct sbi_ecall_extension ecall_cppc;
extern struct sbi_ecall_extension ecall_fwft;
extern struct sbi_ecall_extension ecall_legacy;
extern struct sbi_ecall_extension ecall_vendor;
extern struct sbi_ecall_extension ecall_dbtr;
extern struct sbi_ecall_extension ecall_sse;
extern struct sbi_ecall_extension ecall_mpxy;

struct sbi_ecall_extension *const sbi_ecall_exts[] = {
	&ecall_time,
	&ecall_rfence,
	&ecall_ipi,
	&ecall_base,
	&ecall_hsm,
	&ecall_srst,
	&ecall_susp,
	&ecall_pmu,
	&ecall_dbcn,
	&ecall_cppc,
	&ecall_fwft,
	&ecall_legacy,
	&ecall_vendor,
	&ecall_dbtr,
	&ecall_sse,
	&ecall_mpxy,
	NULL
};
