// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/gpio/fdt_gpio_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/gpio/fdt_gpio.h>

extern const struct fdt_gpio fdt_gpio_designware;
extern const struct fdt_gpio fdt_gpio_sifive;
extern const struct fdt_gpio fdt_gpio_starfive;

const struct fdt_driver *const fdt_gpio_drivers[] = {
	&fdt_gpio_designware.driver,
	&fdt_gpio_sifive.driver,
	&fdt_gpio_starfive.driver,
	NULL
};
