// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/reset/fdt_reset_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/reset/fdt_reset.h>

extern const struct fdt_driver fdt_reset_atcwdt200;
extern const struct fdt_driver fdt_poweroff_gpio;
extern const struct fdt_driver fdt_reset_gpio;
extern const struct fdt_driver fdt_reset_htif;
extern const struct fdt_driver fdt_reset_sg2042_mcu;
extern const struct fdt_driver fdt_reset_sunxi_wdt;
extern const struct fdt_driver fdt_syscon_poweroff;
extern const struct fdt_driver fdt_syscon_reboot;
extern const struct fdt_driver fdt_reset_rpmi;

const struct fdt_driver *const fdt_reset_drivers[] = {
	&fdt_reset_atcwdt200,
	&fdt_poweroff_gpio,
	&fdt_reset_gpio,
	&fdt_reset_htif,
	&fdt_reset_sg2042_mcu,
	&fdt_reset_sunxi_wdt,
	&fdt_syscon_poweroff,
	&fdt_syscon_reboot,
	&fdt_reset_rpmi,
	NULL
};
