// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/i2c/fdt_i2c_adapter_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/i2c/fdt_i2c.h>

extern const struct fdt_driver fdt_i2c_adapter_sifive;
extern const struct fdt_driver fdt_i2c_adapter_dw;

const struct fdt_driver *const fdt_i2c_adapter_drivers[] = {
	&fdt_i2c_adapter_sifive,
	&fdt_i2c_adapter_dw,
	NULL
};
