#!/usr/bin/env python3
"""Generates bazel/mpn.bzl for a GMP module from the GMP source tree.

Parses configure.ac to extract:
  - GMP_MULFUNC_CHOICES  -> ALTERNATIVES dict
  - gmp_mpn_functions    -> GMP_MPN_FUNCTIONS list
  - gmp_mpn_functions_optional -> GMP_MPN_FUNCTIONS_OPTIONAL list

Usage:
    python3 modules/gmp/generate_gmp_defs.py /path/to/gmp-source
    python3 modules/gmp/generate_gmp_defs.py /path/to/gmp-source --version 6.3.0
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


def _re_extract(pattern: str, text: str) -> str:
    m = re.search(pattern, text)
    if not m:
        raise ValueError(f"Pattern not found: {pattern}")
    return m.group(1)


def parse_version(source_dir: Path) -> str:
    """Extract version from gmp-h.in."""
    text = (source_dir / "gmp-h.in").read_text()
    major = _re_extract(r"__GNU_MP_VERSION\s+(\d+)", text)
    minor = _re_extract(r"__GNU_MP_VERSION_MINOR\s+(\d+)", text)
    patch = _re_extract(r"__GNU_MP_VERSION_PATCHLEVEL\s+(\d+)", text)
    return f"{major}.{minor}.{patch}"


def parse_shell_wordlist(text: str) -> list[str]:
    """Parse a shell variable assignment spanning continuation lines."""
    text = text.replace("\\\n", " ")
    text = re.sub(r"#.*", "", text)
    return text.split()


def parse_functions(configure_ac: str) -> tuple[list[str], list[str]]:
    """Extract gmp_mpn_functions and gmp_mpn_functions_optional."""
    optional_match = re.search(r'gmp_mpn_functions_optional="([^"]+)"', configure_ac, re.DOTALL)
    optional = parse_shell_wordlist(optional_match.group(1)) if optional_match else []

    main_match = re.search(
        r'gmp_mpn_functions="\$extra_functions\s+(.*?)\$gmp_mpn_functions_optional"',
        configure_ac,
        re.DOTALL,
    )
    main = parse_shell_wordlist(main_match.group(1)) if main_match else []

    return main, optional


def parse_mulfunc_choices(configure_ac: str) -> dict[str, list[str]]:
    """Extract GMP_MULFUNC_CHOICES case statement into an alternatives dict."""
    match = re.search(
        r"define\(GMP_MULFUNC_CHOICES,\s*\[.*?case \$tmp_fn in\s*(.*?)\besac",
        configure_ac,
        re.DOTALL,
    )
    if not match:
        return {}

    block = match.group(1)
    alternatives: dict[str, list[str]] = {}

    for case_match in re.finditer(
        r"([\w|\s]+?)\)\s*tmp_mulfunc=\"([^\"]+)\"",
        block,
    ):
        raw = re.sub(r"\s+", "", case_match.group(1))
        funcs = [f for f in raw.split("|") if f]
        alts = case_match.group(2).split()
        for fn in funcs:
            alternatives[fn] = alts

    return alternatives


_EXTRA_FUNCTIONS_EXCLUDE = {"fat", "fat_entry"}


def parse_extra_functions(configure_ac: str) -> list[str]:
    """Extract extra_functions relevant to x86_64/arm64.

    Looks for extra_functions_64 assignments (used by x86_64).
    Excludes fat-binary-only functions.
    Returns a flat deduplicated list.
    """
    extras: list[str] = []
    for match in re.finditer(
        r'extra_functions_64="\$extra_functions_64\s+(\w[\w\s]*)"',
        configure_ac,
    ):
        for fn in match.group(1).split():
            if fn not in extras and fn not in _EXTRA_FUNCTIONS_EXCLUDE:
                extras.append(fn)
    return extras


def format_dict(d: dict[str, list[str]], indent: int = 4) -> str:
    """Format a dict as a Starlark literal."""
    pad = " " * indent
    lines = ["{"]
    for k, v in sorted(d.items()):
        lines.append(f'{pad}"{k}": {v!r},')
    lines.append("}")
    return "\n".join(lines)


def format_list(items: list[str], indent: int = 4) -> str:
    """Format a list as a Starlark literal."""
    pad = " " * indent
    lines = ["["]
    for item in items:
        lines.append(f'{pad}"{item}",')
    lines.append("]")
    return "\n".join(lines)


def generate_bzl(
    alternatives: dict[str, list[str]],
    functions: list[str],
    optional: list[str],
) -> str:
    """Generate the mpn.bzl content."""
    return (
        '"""GMP MPN definitions -- generated by generate_gmp_defs.py, do not edit."""\n'
        "\n"
        "# Multi-function file alternatives (from configure.ac GMP_MULFUNC_CHOICES).\n"
        "# Maps a function name to alternative filenames that may provide it.\n"
        f"ALTERNATIVES = {format_dict(alternatives)}\n"
        "\n"
        "# Mandatory MPN functions (from configure.ac gmp_mpn_functions).\n"
        f"GMP_MPN_FUNCTIONS = {format_list(functions)}\n"
        "\n"
        "# Optional MPN functions (from configure.ac gmp_mpn_functions_optional).\n"
        "# Only compiled when an architecture-specific implementation exists.\n"
        f"GMP_MPN_FUNCTIONS_OPTIONAL = {format_list(optional)}\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_dir", type=Path, help="Path to GMP source tree")
    parser.add_argument("--version", help="GMP version (derived from source if omitted)")
    parser.add_argument(
        "--bcr-root",
        type=Path,
        default=Path(__file__).resolve().parent.parent.parent,
        help="Path to bazel-central-registry root",
    )
    args = parser.parse_args()

    source_dir = args.source_dir.resolve()
    if not (source_dir / "configure.ac").exists():
        parser.error(f"No configure.ac found in {source_dir}")

    version = args.version or parse_version(source_dir)
    configure_ac = (source_dir / "configure.ac").read_text()

    functions, optional = parse_functions(configure_ac)
    alternatives = parse_mulfunc_choices(configure_ac)
    extras = parse_extra_functions(configure_ac)

    for fn in extras:
        if fn not in optional:
            optional.append(fn)

    bzl_content = generate_bzl(alternatives, functions, optional)

    out_dir = args.bcr_root / "modules" / "gmp" / version / "overlay" / "bazel"
    if not out_dir.exists():
        parser.error(f"Module directory not found: {out_dir}")

    out_path = out_dir / "mpn.bzl"
    out_path.write_text(bzl_content)
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
