// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/regmap/fdt_regmap_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/regmap/fdt_regmap.h>

extern const struct fdt_driver fdt_regmap_syscon;

const struct fdt_driver *const fdt_regmap_drivers[] = {
	&fdt_regmap_syscon,
	NULL
};
