/* Linux configuration for the pinned BCR dependencies. No host probes. */
#ifndef PANGO_BAZEL_CONFIG_H
#define PANGO_BAZEL_CONFIG_H
#define PANGO_BINARY_AGE 5201
#define PANGO_INTERFACE_AGE 1
#define PANGO_VERSION_MAJOR 1
#define PANGO_VERSION_MINOR 52
#define PANGO_VERSION_MICRO 1
#define HAVE_FREETYPE 1
#define HAVE_FCWEIGHTFROMOPENTYPEDOUBLE 1
#define HAVE_CAIRO 1
#define HAVE_CAIRO_FREETYPE 1
#define HAVE_CAIRO_PNG 1
#define HAVE_CAIRO_PS 1
#define HAVE_CAIRO_PDF 1
#define HAVE_LIBTHAI 1
#define HAVE_TH_BRK_FIND_BREAKS 1
#undef HAVE_SYSPROF
#endif
