"""The ld configuration of binutils 2.47, per platform of //:targets.bzl.

GENERATED by modules/binutils/generate_targets.py; do not edit.  Results
identical between platforms are shared, named after the first platform using them.
"""

visibility(["//..."])

_LD_LINUX_X86_64 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "yes",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": True,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_x86_64\\\"\"",
        "TARGET=\"\\\"x86_64-pc-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf_x86_64",
        "elf_i386",
        "elf32_x86_64",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_x86_64",
        "elf_i386",
        "elf32_x86_64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf_i386": "i386-pc-linux-gnu",
    },
}

_LD_LINUX_X86_32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "yes",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": True,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf_i386\\\"\"",
        "TARGET=\"\\\"i686-pc-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf_i386",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_LINUX_AARCH64 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"aarch64linux\\\"\"",
        "TARGET=\"\\\"aarch64-unknown-linux-gnu\\\"\"",
    ],
    "emulations": [
        "aarch64linux",
        "aarch64linuxb",
        "aarch64linux32",
        "aarch64linux32b",
        "armelfb_linux_eabi",
        "armelf_linux_eabi",
        "aarch64elf",
        "aarch64elf32",
        "aarch64elf32b",
        "aarch64elfb",
        "armelf",
        "armelfb",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "aarch64linux",
        "aarch64linuxb",
        "aarch64linux32",
        "aarch64linux32b",
        "armelfb_linux_eabi",
        "armelf_linux_eabi",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_LINUX_AARCH32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_linux_eabi\\\"\"",
        "TARGET=\"\\\"arm-unknown-linux-gnueabi\\\"\"",
    ],
    "emulations": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_LINUX_ARMV7 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_linux_eabi\\\"\"",
        "TARGET=\"\\\"armv7-unknown-linux-gnueabihf\\\"\"",
    ],
    "emulations": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_LINUX_PPC = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64ppc\\\"\"",
        "TARGET=\"\\\"powerpc64-unknown-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-linux-gnu",
        "elf32lppclinux": "powerpcle-unknown-linux-gnu",
        "elf32lppcsim": "powerpcle-unknown-linux-gnu",
        "elf32ppc": "powerpc-unknown-linux-gnu",
        "elf32ppclinux": "powerpc-unknown-linux-gnu",
        "elf32ppcsim": "powerpc-unknown-linux-gnu",
        "elf64lppc": "powerpc64le-unknown-linux-gnu",
    },
}

_LD_LINUX_PPC32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppclinux\\\"\"",
        "TARGET=\"\\\"powerpc-unknown-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf32ppclinux",
        "elf32ppc",
        "elf32lppclinux",
        "elf32lppc",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppclinux",
        "elf32ppc",
        "elf32lppclinux",
        "elf32lppc",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-linux-gnu",
        "elf32lppclinux": "powerpcle-unknown-linux-gnu",
        "elf32lppcsim": "powerpcle-unknown-linux-gnu",
    },
}

_LD_LINUX_PPC64LE = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lppc\\\"\"",
        "TARGET=\"\\\"powerpc64le-unknown-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppcsim",
        "elf32ppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-linux-gnu",
        "elf32lppclinux": "powerpcle-unknown-linux-gnu",
        "elf32lppcsim": "powerpcle-unknown-linux-gnu",
        "elf32ppc": "powerpc-unknown-linux-gnu",
        "elf32ppclinux": "powerpc-unknown-linux-gnu",
        "elf32ppcsim": "powerpc-unknown-linux-gnu",
        "elf64ppc": "powerpc64-unknown-linux-gnu",
    },
}

_LD_LINUX_S390X = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf64_s390\\\"\"",
        "TARGET=\"\\\"s390x-ibm-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf64_s390",
        "elf_s390",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64_s390",
        "elf_s390",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf_s390": "s390-ibm-linux-gnu",
    },
}

_LD_LINUX_MIPS64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "0",
        "warn_rwx_segments": False,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64btsmip\\\"\"",
        "TARGET=\"\\\"mips64-unknown-linux-gnuabi64\\\"\"",
    ],
    "emulations": [
        "elf64btsmip",
        "elf64ltsmip",
        "elf32btsmipn32",
        "elf32ltsmipn32",
        "elf32btsmip",
        "elf32ltsmip",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64btsmip",
        "elf64ltsmip",
        "elf32btsmipn32",
        "elf32ltsmipn32",
        "elf32btsmip",
        "elf32ltsmip",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_LINUX_RISCV32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32lriscv\\\"\"",
        "TARGET=\"\\\"riscv32-unknown-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf32lriscv",
        "elf32lriscv_ilp32f",
        "elf32lriscv_ilp32",
        "elf64lriscv",
        "elf64lriscv_lp64f",
        "elf64lriscv_lp64",
        "elf32briscv",
        "elf32briscv_ilp32f",
        "elf32briscv_ilp32",
        "elf64briscv",
        "elf64briscv_lp64f",
        "elf64briscv_lp64",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32lriscv",
        "elf32lriscv_ilp32f",
        "elf32lriscv_ilp32",
        "elf64lriscv",
        "elf64lriscv_lp64f",
        "elf64lriscv_lp64",
        "elf32briscv",
        "elf32briscv_ilp32f",
        "elf32briscv_ilp32",
        "elf64briscv",
        "elf64briscv_lp64f",
        "elf64briscv_lp64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_LINUX_RISCV64 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lriscv\\\"\"",
        "TARGET=\"\\\"riscv64-unknown-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf64lriscv",
        "elf64lriscv_lp64f",
        "elf64lriscv_lp64",
        "elf32lriscv",
        "elf32lriscv_ilp32f",
        "elf32lriscv_ilp32",
        "elf64briscv",
        "elf64briscv_lp64f",
        "elf64briscv_lp64",
        "elf32briscv",
        "elf32briscv_ilp32f",
        "elf32briscv_ilp32",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lriscv",
        "elf64lriscv_lp64f",
        "elf64lriscv_lp64",
        "elf32lriscv",
        "elf32lriscv_ilp32f",
        "elf32lriscv_ilp32",
        "elf64briscv",
        "elf64briscv_lp64f",
        "elf64briscv_lp64",
        "elf32briscv",
        "elf32briscv_ilp32f",
        "elf32briscv_ilp32",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_ANDROID_X86_64 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "yes",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": True,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_x86_64\\\"\"",
        "TARGET=\"\\\"x86_64-pc-linux-android\\\"\"",
    ],
    "emulations": [
        "elf_x86_64",
        "elf_i386",
        "elf32_x86_64",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_x86_64",
        "elf_i386",
        "elf32_x86_64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf_i386": "i386-pc-linux-android",
    },
}

_LD_ANDROID_X86_32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "yes",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": True,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf_i386\\\"\"",
        "TARGET=\"\\\"i686-pc-linux-android\\\"\"",
    ],
    "emulations": [
        "elf_i386",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_ANDROID_AARCH64 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"aarch64linux\\\"\"",
        "TARGET=\"\\\"aarch64-unknown-linux-android\\\"\"",
    ],
    "emulations": [
        "aarch64linux",
        "aarch64linuxb",
        "aarch64linux32",
        "aarch64linux32b",
        "armelfb_linux_eabi",
        "armelf_linux_eabi",
        "aarch64elf",
        "aarch64elf32",
        "aarch64elf32b",
        "aarch64elfb",
        "armelf",
        "armelfb",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "aarch64linux",
        "aarch64linuxb",
        "aarch64linux32",
        "aarch64linux32b",
        "armelfb_linux_eabi",
        "armelf_linux_eabi",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_ANDROID_AARCH32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_linux_eabi\\\"\"",
        "TARGET=\"\\\"arm-unknown-linux-androideabi\\\"\"",
    ],
    "emulations": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_ANDROID_ARMV7 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_linux_eabi\\\"\"",
        "TARGET=\"\\\"armv7-unknown-linux-androideabi\\\"\"",
    ],
    "emulations": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_linux_eabi",
        "armelfb_linux_eabi",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_ANDROID_RISCV64 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lriscv\\\"\"",
        "TARGET=\"\\\"riscv64-unknown-linux-android\\\"\"",
    ],
    "emulations": [
        "elf64lriscv",
        "elf64lriscv_lp64f",
        "elf64lriscv_lp64",
        "elf32lriscv",
        "elf32lriscv_ilp32f",
        "elf32lriscv_ilp32",
        "elf64briscv",
        "elf64briscv_lp64f",
        "elf64briscv_lp64",
        "elf32briscv",
        "elf32briscv_ilp32f",
        "elf32briscv_ilp32",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lriscv",
        "elf64lriscv_lp64f",
        "elf64lriscv_lp64",
        "elf32lriscv",
        "elf32lriscv_ilp32f",
        "elf32lriscv_ilp32",
        "elf64briscv",
        "elf64briscv_lp64f",
        "elf64briscv_lp64",
        "elf32briscv",
        "elf32briscv_ilp32f",
        "elf32briscv_ilp32",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_WINDOWS_X86_64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=false",
        "ELF_SHLIB_LIST_OPTIONS=false",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"i386pep\\\"\"",
        "TARGET=\"\\\"x86_64-w64-mingw32\\\"\"",
    ],
    "emulations": [
        "i386pep",
        "i386pe",
    ],
    "extra_srcs": [
        "deffilep.c",
        "pdb.c",
        "pep-dll.c",
        "pe-dll.c",
    ],
    "libpath": [
        "i386pep",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_WINDOWS_X86_32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=false",
        "ELF_SHLIB_LIST_OPTIONS=false",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"i386pe\\\"\"",
        "TARGET=\"\\\"i686-w64-mingw32\\\"\"",
    ],
    "emulations": [
        "i386pe",
    ],
    "extra_srcs": [
        "deffilep.c",
        "pdb.c",
        "pe-dll.c",
    ],
    "libpath": [
        "i386pe",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_WINDOWS_AARCH64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=false",
        "ELF_SHLIB_LIST_OPTIONS=false",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"aarch64pe\\\"\"",
        "TARGET=\"\\\"aarch64-w64-mingw32\\\"\"",
    ],
    "emulations": [
        "aarch64pe",
        "arm64pe",
    ],
    "extra_srcs": [
        "deffilep.c",
        "pep-dll.c",
        "pe-dll.c",
        "pdb.c",
    ],
    "libpath": [
        "aarch64pe",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_FREEBSD_X86_64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_x86_64_fbsd\\\"\"",
        "TARGET=\"\\\"x86_64-pc-freebsd\\\"\"",
    ],
    "emulations": [
        "elf_x86_64_fbsd",
        "elf_i386_fbsd",
        "elf_x86_64",
        "elf_i386",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_x86_64_fbsd",
        "elf_i386_fbsd",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {
        "elf_i386": "i386-pc-freebsd",
        "elf_i386_fbsd": "i386-pc-freebsd",
    },
}

_LD_FREEBSD_X86_32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf_i386_fbsd\\\"\"",
        "TARGET=\"\\\"i686-pc-freebsd\\\"\"",
    ],
    "emulations": [
        "elf_i386_fbsd",
        "elf_i386",
        "i386bsd",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386_fbsd",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_FREEBSD_AARCH64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"aarch64fbsd\\\"\"",
        "TARGET=\"\\\"aarch64-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "aarch64fbsd",
        "aarch64fbsdb",
        "aarch64elf",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "aarch64fbsd",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_FREEBSD_AARCH32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_fbsd\\\"\"",
        "TARGET=\"\\\"arm-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "armelf_fbsd",
        "armelfb_fbsd",
        "armelf",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_fbsd",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_FREEBSD_ARMV7 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_fbsd\\\"\"",
        "TARGET=\"\\\"armv7-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "armelf_fbsd",
        "armelfb_fbsd",
        "armelf",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_fbsd",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_FREEBSD_PPC = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64ppc_fbsd\\\"\"",
        "TARGET=\"\\\"powerpc64-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "elf64ppc_fbsd",
        "elf32ppc_fbsd",
        "elf32ppc",
        "elf64ppc",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64ppc_fbsd",
        "elf32ppc_fbsd",
        "elf32ppc",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {
        "elf32ppc": "powerpc-unknown-freebsd",
        "elf32ppc_fbsd": "powerpc-unknown-freebsd",
    },
}

_LD_FREEBSD_PPC32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppc_fbsd\\\"\"",
        "TARGET=\"\\\"powerpc-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "elf32ppc_fbsd",
        "elf32ppc",
        "elf32ppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppc_fbsd",
        "elf32ppc",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_FREEBSD_PPC64LE = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lppc_fbsd\\\"\"",
        "TARGET=\"\\\"powerpc64le-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "elf64lppc_fbsd",
        "elf64lppc",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lppc_fbsd",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_FREEBSD_MIPS64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "0",
        "warn_rwx_segments": False,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32btsmipn32_fbsd\\\"\"",
        "TARGET=\"\\\"mips64-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "elf32btsmipn32_fbsd",
        "elf32ltsmip",
        "elf32btsmip",
        "elf32ltsmipn32",
        "elf32btsmipn32",
        "elf64ltsmip",
        "elf64btsmip",
        "elf32ltsmip_fbsd",
        "elf32btsmip_fbsd",
        "elf32ltsmipn32_fbsd",
        "elf64ltsmip_fbsd",
        "elf64btsmip_fbsd",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32btsmipn32_fbsd",
        "elf32ltsmip",
        "elf32btsmip",
        "elf32ltsmipn32",
        "elf32btsmipn32",
        "elf64ltsmip",
        "elf64btsmip",
        "elf32ltsmip_fbsd",
        "elf32btsmip_fbsd",
        "elf32ltsmipn32_fbsd",
        "elf64ltsmip_fbsd",
        "elf64btsmip_fbsd",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_FREEBSD_RISCV64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lriscv\\\"\"",
        "TARGET=\"\\\"riscv64-unknown-freebsd\\\"\"",
    ],
    "emulations": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "native_lib_dirs": [
        "/lib",
        "/usr/lib",
        "/usr/local/lib",
        "/usr/lib32",
    ],
    "tdirs": {},
}

_LD_NETBSD_X86_64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_x86_64\\\"\"",
        "TARGET=\"\\\"x86_64-pc-netbsd\\\"\"",
    ],
    "emulations": [
        "elf_x86_64",
        "elf_i386",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_x86_64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf_i386": "i386-pc-netbsd",
    },
}

_LD_NETBSD_X86_32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf_i386\\\"\"",
        "TARGET=\"\\\"i686-pc-netbsd\\\"\"",
    ],
    "emulations": [
        "elf_i386",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_NETBSD_AARCH32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_nbsd\\\"\"",
        "TARGET=\"\\\"arm-unknown-netbsd\\\"\"",
    ],
    "emulations": [
        "armelf_nbsd",
        "armelfb_nbsd",
        "armelf",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_nbsd",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_NETBSD_PPC = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64ppc\\\"\"",
        "TARGET=\"\\\"powerpc64-unknown-netbsd\\\"\"",
    ],
    "emulations": [
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-netbsd",
        "elf32lppclinux": "powerpcle-unknown-netbsd",
        "elf32lppcsim": "powerpcle-unknown-netbsd",
        "elf32ppc": "powerpc-unknown-netbsd",
        "elf32ppclinux": "powerpc-unknown-netbsd",
        "elf32ppcsim": "powerpc-unknown-netbsd",
        "elf64lppc": "powerpc64le-unknown-netbsd",
    },
}

_LD_NETBSD_PPC32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppc\\\"\"",
        "TARGET=\"\\\"powerpc-unknown-netbsd\\\"\"",
    ],
    "emulations": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-netbsd",
        "elf32lppclinux": "powerpcle-unknown-netbsd",
        "elf32lppcsim": "powerpcle-unknown-netbsd",
    },
}

_LD_NETBSD_MIPS64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "0",
        "warn_rwx_segments": False,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32btsmip\\\"\"",
        "TARGET=\"\\\"mips64-unknown-netbsd\\\"\"",
    ],
    "emulations": [
        "elf32btsmip",
        "elf32ltsmip",
        "elf64btsmip",
        "elf64ltsmip",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32btsmip",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_NETBSD_RISCV64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lriscv\\\"\"",
        "TARGET=\"\\\"riscv64-unknown-netbsd\\\"\"",
    ],
    "emulations": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_OPENBSD_X86_64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_x86_64\\\"\"",
        "TARGET=\"\\\"x86_64-pc-openbsd\\\"\"",
    ],
    "emulations": [
        "elf_x86_64",
        "elf_i386",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_x86_64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf_i386": "i386-pc-openbsd",
    },
}

_LD_OPENBSD_X86_32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf_i386\\\"\"",
        "TARGET=\"\\\"i686-pc-openbsd\\\"\"",
    ],
    "emulations": [
        "elf_i386",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_OPENBSD_PPC = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64ppc\\\"\"",
        "TARGET=\"\\\"powerpc64-unknown-openbsd\\\"\"",
    ],
    "emulations": [
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64ppc",
        "elf32ppc",
        "elf32ppclinux",
        "elf64lppc",
        "elf32lppc",
        "elf32lppclinux",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-openbsd",
        "elf32lppclinux": "powerpcle-unknown-openbsd",
        "elf32lppcsim": "powerpcle-unknown-openbsd",
        "elf32ppc": "powerpc-unknown-openbsd",
        "elf32ppclinux": "powerpc-unknown-openbsd",
        "elf32ppcsim": "powerpc-unknown-openbsd",
        "elf64lppc": "powerpc64le-unknown-openbsd",
    },
}

_LD_OPENBSD_PPC32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppc\\\"\"",
        "TARGET=\"\\\"powerpc-unknown-openbsd\\\"\"",
    ],
    "emulations": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-openbsd",
        "elf32lppclinux": "powerpcle-unknown-openbsd",
        "elf32lppcsim": "powerpcle-unknown-openbsd",
    },
}

_LD_OPENBSD_MIPS64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "0",
        "warn_rwx_segments": False,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64btsmip\\\"\"",
        "TARGET=\"\\\"mips64-unknown-openbsd\\\"\"",
    ],
    "emulations": [
        "elf64btsmip",
        "elf64ltsmip",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64btsmip",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_OPENBSD_RISCV64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lriscv\\\"\"",
        "TARGET=\"\\\"riscv64-unknown-openbsd\\\"\"",
    ],
    "emulations": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_HAIKU_X86_64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_x86_64_haiku\\\"\"",
        "TARGET=\"\\\"x86_64-unknown-haiku\\\"\"",
    ],
    "emulations": [
        "elf_x86_64_haiku",
        "elf_x86_64",
        "elf_i386_haiku",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_x86_64_haiku",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_HAIKU_X86_32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf_i386_haiku\\\"\"",
        "TARGET=\"\\\"i686-unknown-haiku\\\"\"",
    ],
    "emulations": [
        "elf_i386_haiku",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386_haiku",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_VXWORKS_X86_32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf_i386_vxworks\\\"\"",
        "TARGET=\"\\\"i686-wrs-vxworks\\\"\"",
    ],
    "emulations": [
        "elf_i386_vxworks",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386_vxworks",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_VXWORKS_AARCH32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armelf_vxworks\\\"\"",
        "TARGET=\"\\\"arm-wrs-vxworks\\\"\"",
    ],
    "emulations": [
        "armelf_vxworks",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armelf_vxworks",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_VXWORKS_PPC32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppcvxworks\\\"\"",
        "TARGET=\"\\\"powerpc-wrs-vxworks\\\"\"",
    ],
    "emulations": [
        "elf32ppcvxworks",
        "elf32ppc",
        "elf32ppclinux",
        "elf32ppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppcvxworks",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_VXWORKS_MIPS64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "0",
        "warn_rwx_segments": False,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ebmipvxworks\\\"\"",
        "TARGET=\"\\\"mips64-wrs-vxworks\\\"\"",
    ],
    "emulations": [
        "elf32ebmipvxworks",
        "elf32elmipvxworks",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ebmipvxworks",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_QNX_X86_32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"i386nto\\\"\"",
        "TARGET=\"\\\"i686-pc-nto-qnx\\\"\"",
    ],
    "emulations": [
        "i386nto",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "i386nto",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_QNX_AARCH64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"aarch64nto\\\"\"",
        "TARGET=\"\\\"aarch64-pc-nto-qnx\\\"\"",
    ],
    "emulations": [
        "aarch64nto",
        "aarch64elf",
        "aarch64elf32",
        "aarch64elf32b",
        "aarch64elfb",
        "armelf",
        "armelfb",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "aarch64nto",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_QNX_AARCH32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"armnto\\\"\"",
        "TARGET=\"\\\"arm-pc-nto-qnx\\\"\"",
    ],
    "emulations": [
        "armnto",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "armnto",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_QNX_PPC32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppcnto\\\"\"",
        "TARGET=\"\\\"powerpc-pc-nto-qnx\\\"\"",
    ],
    "emulations": [
        "elf32ppcnto",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppcnto",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_FUCHSIA_X86_64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_x86_64\\\"\"",
        "TARGET=\"\\\"x86_64-unknown-fuchsia\\\"\"",
    ],
    "emulations": [
        "elf_x86_64",
        "elf_i386",
        "elf32_x86_64",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_x86_64",
        "elf_i386",
        "elf32_x86_64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf_i386": "i386-unknown-fuchsia",
    },
}

_LD_FUCHSIA_AARCH64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"aarch64elf\\\"\"",
        "TARGET=\"\\\"aarch64-unknown-fuchsia\\\"\"",
    ],
    "emulations": [
        "aarch64elf",
        "aarch64elfb",
        "armelf",
        "armelfb",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "aarch64elf",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_FUCHSIA_RISCV64 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=false",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf64lriscv\\\"\"",
        "TARGET=\"\\\"riscv64-unknown-fuchsia\\\"\"",
    ],
    "emulations": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf64lriscv",
        "elf32lriscv",
        "elf64briscv",
        "elf32briscv",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_64_LINUX_X86_32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "yes",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": True,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_i386\\\"\"",
        "TARGET=\"\\\"i686-pc-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf_i386",
        "elf_x86_64",
        "elf32_x86_64",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386",
        "elf_x86_64",
        "elf32_x86_64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_64_LINUX_PPC32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppclinux\\\"\"",
        "TARGET=\"\\\"powerpc-unknown-linux-gnu\\\"\"",
    ],
    "emulations": [
        "elf32ppclinux",
        "elf32ppc",
        "elf32lppclinux",
        "elf32lppc",
        "elf64ppc",
        "elf64lppc",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppclinux",
        "elf32ppc",
        "elf32lppclinux",
        "elf32lppc",
        "elf64ppc",
        "elf64lppc",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-linux-gnu",
        "elf32lppclinux": "powerpcle-unknown-linux-gnu",
        "elf32lppcsim": "powerpcle-unknown-linux-gnu",
        "elf64lppc": "powerpc64le-unknown-linux-gnu",
        "elf64ppc": "powerpc64-unknown-linux-gnu",
    },
}

_LD_64_ANDROID_X86_32 = {
    "defaults": {
        "hash_style": "both",
        "textrel_check": "yes",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": True,
        "z_separate_code": True,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=true",
        "DEFAULT_EMULATION=\"\\\"elf_i386\\\"\"",
        "TARGET=\"\\\"i686-pc-linux-android\\\"\"",
    ],
    "emulations": [
        "elf_i386",
        "elf_x86_64",
        "elf32_x86_64",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf_i386",
        "elf_x86_64",
        "elf32_x86_64",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {},
}

_LD_64_NETBSD_PPC32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppc\\\"\"",
        "TARGET=\"\\\"powerpc-unknown-netbsd\\\"\"",
    ],
    "emulations": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
        "elf64ppc",
        "elf64lppc",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
        "elf64ppc",
        "elf64lppc",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-netbsd",
        "elf32lppclinux": "powerpcle-unknown-netbsd",
        "elf32lppcsim": "powerpcle-unknown-netbsd",
        "elf64lppc": "powerpc64le-unknown-netbsd",
        "elf64ppc": "powerpc64-unknown-netbsd",
    },
}

_LD_64_OPENBSD_PPC32 = {
    "defaults": {
        "hash_style": "sysv",
        "textrel_check": "unset",
        "warn_execstack": "2",
        "warn_rwx_segments": True,
        "z_relro": False,
        "z_separate_code": False,
    },
    "defines": [
        "ELF_LIST_OPTIONS=true",
        "ELF_SHLIB_LIST_OPTIONS=true",
        "ELF_PLT_UNWIND_LIST_OPTIONS=true",
        "ELF_SFRAME_LIST_OPTIONS=false",
        "DEFAULT_EMULATION=\"\\\"elf32ppc\\\"\"",
        "TARGET=\"\\\"powerpc-unknown-openbsd\\\"\"",
    ],
    "emulations": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
        "elf64ppc",
        "elf64lppc",
        "elf32ppcsim",
        "elf32lppcsim",
    ],
    "extra_srcs": [
        "ldelf.c",
        "ldelfgen.c",
    ],
    "libpath": [
        "elf32ppc",
        "elf32ppclinux",
        "elf32lppc",
        "elf32lppclinux",
        "elf64ppc",
        "elf64lppc",
    ],
    "native_lib_dirs": [
        "/usr/local/lib",
        "/lib",
        "/usr/lib",
    ],
    "tdirs": {
        "elf32lppc": "powerpcle-unknown-openbsd",
        "elf32lppclinux": "powerpcle-unknown-openbsd",
        "elf32lppcsim": "powerpcle-unknown-openbsd",
        "elf64lppc": "powerpc64le-unknown-openbsd",
        "elf64ppc": "powerpc64-unknown-openbsd",
    },
}

LD = {
    "android_aarch32": _LD_ANDROID_AARCH32,
    "android_aarch64": _LD_ANDROID_AARCH64,
    "android_armv7": _LD_ANDROID_ARMV7,
    "android_i386": _LD_ANDROID_X86_32,
    "android_riscv64": _LD_ANDROID_RISCV64,
    "android_x86_32": _LD_ANDROID_X86_32,
    "android_x86_64": _LD_ANDROID_X86_64,
    "chromiumos_aarch32": _LD_LINUX_AARCH32,
    "chromiumos_aarch64": _LD_LINUX_AARCH64,
    "chromiumos_armv7": _LD_LINUX_ARMV7,
    "chromiumos_i386": _LD_LINUX_X86_32,
    "chromiumos_x86_32": _LD_LINUX_X86_32,
    "chromiumos_x86_64": _LD_LINUX_X86_64,
    "freebsd_aarch32": _LD_FREEBSD_AARCH32,
    "freebsd_aarch64": _LD_FREEBSD_AARCH64,
    "freebsd_armv7": _LD_FREEBSD_ARMV7,
    "freebsd_i386": _LD_FREEBSD_X86_32,
    "freebsd_mips64": _LD_FREEBSD_MIPS64,
    "freebsd_ppc": _LD_FREEBSD_PPC,
    "freebsd_ppc32": _LD_FREEBSD_PPC32,
    "freebsd_ppc64le": _LD_FREEBSD_PPC64LE,
    "freebsd_riscv64": _LD_FREEBSD_RISCV64,
    "freebsd_x86_32": _LD_FREEBSD_X86_32,
    "freebsd_x86_64": _LD_FREEBSD_X86_64,
    "fuchsia_aarch64": _LD_FUCHSIA_AARCH64,
    "fuchsia_riscv64": _LD_FUCHSIA_RISCV64,
    "fuchsia_x86_64": _LD_FUCHSIA_X86_64,
    "haiku_i386": _LD_HAIKU_X86_32,
    "haiku_x86_32": _LD_HAIKU_X86_32,
    "haiku_x86_64": _LD_HAIKU_X86_64,
    "linux_aarch32": _LD_LINUX_AARCH32,
    "linux_aarch64": _LD_LINUX_AARCH64,
    "linux_armv7": _LD_LINUX_ARMV7,
    "linux_i386": _LD_LINUX_X86_32,
    "linux_mips64": _LD_LINUX_MIPS64,
    "linux_ppc": _LD_LINUX_PPC,
    "linux_ppc32": _LD_LINUX_PPC32,
    "linux_ppc64le": _LD_LINUX_PPC64LE,
    "linux_riscv32": _LD_LINUX_RISCV32,
    "linux_riscv64": _LD_LINUX_RISCV64,
    "linux_s390x": _LD_LINUX_S390X,
    "linux_x86_32": _LD_LINUX_X86_32,
    "linux_x86_64": _LD_LINUX_X86_64,
    "macos_aarch64": None,
    "macos_x86_64": None,
    "netbsd_aarch32": _LD_NETBSD_AARCH32,
    "netbsd_aarch64": None,
    "netbsd_armv7": _LD_NETBSD_AARCH32,
    "netbsd_i386": _LD_NETBSD_X86_32,
    "netbsd_mips64": _LD_NETBSD_MIPS64,
    "netbsd_ppc": _LD_NETBSD_PPC,
    "netbsd_ppc32": _LD_NETBSD_PPC32,
    "netbsd_riscv64": _LD_NETBSD_RISCV64,
    "netbsd_x86_32": _LD_NETBSD_X86_32,
    "netbsd_x86_64": _LD_NETBSD_X86_64,
    "nixos_aarch32": _LD_LINUX_AARCH32,
    "nixos_aarch64": _LD_LINUX_AARCH64,
    "nixos_armv7": _LD_LINUX_ARMV7,
    "nixos_i386": _LD_LINUX_X86_32,
    "nixos_mips64": _LD_LINUX_MIPS64,
    "nixos_ppc": _LD_LINUX_PPC,
    "nixos_ppc32": _LD_LINUX_PPC32,
    "nixos_ppc64le": _LD_LINUX_PPC64LE,
    "nixos_riscv32": _LD_LINUX_RISCV32,
    "nixos_riscv64": _LD_LINUX_RISCV64,
    "nixos_s390x": _LD_LINUX_S390X,
    "nixos_x86_32": _LD_LINUX_X86_32,
    "nixos_x86_64": _LD_LINUX_X86_64,
    "openbsd_aarch32": None,
    "openbsd_aarch64": None,
    "openbsd_armv7": None,
    "openbsd_i386": _LD_OPENBSD_X86_32,
    "openbsd_mips64": _LD_OPENBSD_MIPS64,
    "openbsd_ppc": _LD_OPENBSD_PPC,
    "openbsd_ppc32": _LD_OPENBSD_PPC32,
    "openbsd_riscv64": _LD_OPENBSD_RISCV64,
    "openbsd_x86_32": _LD_OPENBSD_X86_32,
    "openbsd_x86_64": _LD_OPENBSD_X86_64,
    "qnx_aarch32": _LD_QNX_AARCH32,
    "qnx_aarch64": _LD_QNX_AARCH64,
    "qnx_armv7": _LD_QNX_AARCH32,
    "qnx_i386": _LD_QNX_X86_32,
    "qnx_ppc32": _LD_QNX_PPC32,
    "qnx_x86_32": _LD_QNX_X86_32,
    "vxworks_aarch32": _LD_VXWORKS_AARCH32,
    "vxworks_armv7": _LD_VXWORKS_AARCH32,
    "vxworks_i386": _LD_VXWORKS_X86_32,
    "vxworks_mips64": _LD_VXWORKS_MIPS64,
    "vxworks_ppc32": _LD_VXWORKS_PPC32,
    "vxworks_x86_32": _LD_VXWORKS_X86_32,
    "windows_aarch64": _LD_WINDOWS_AARCH64,
    "windows_i386": _LD_WINDOWS_X86_32,
    "windows_x86_32": _LD_WINDOWS_X86_32,
    "windows_x86_64": _LD_WINDOWS_X86_64,
}

LD_64 = {
    "android_aarch32": _LD_ANDROID_AARCH32,
    "android_aarch64": _LD_ANDROID_AARCH64,
    "android_armv7": _LD_ANDROID_ARMV7,
    "android_i386": _LD_64_ANDROID_X86_32,
    "android_riscv64": _LD_ANDROID_RISCV64,
    "android_x86_32": _LD_64_ANDROID_X86_32,
    "android_x86_64": _LD_ANDROID_X86_64,
    "chromiumos_aarch32": _LD_LINUX_AARCH32,
    "chromiumos_aarch64": _LD_LINUX_AARCH64,
    "chromiumos_armv7": _LD_LINUX_ARMV7,
    "chromiumos_i386": _LD_64_LINUX_X86_32,
    "chromiumos_x86_32": _LD_64_LINUX_X86_32,
    "chromiumos_x86_64": _LD_LINUX_X86_64,
    "freebsd_aarch32": _LD_FREEBSD_AARCH32,
    "freebsd_aarch64": _LD_FREEBSD_AARCH64,
    "freebsd_armv7": _LD_FREEBSD_ARMV7,
    "freebsd_i386": _LD_FREEBSD_X86_32,
    "freebsd_mips64": _LD_FREEBSD_MIPS64,
    "freebsd_ppc": _LD_FREEBSD_PPC,
    "freebsd_ppc32": _LD_FREEBSD_PPC32,
    "freebsd_ppc64le": _LD_FREEBSD_PPC64LE,
    "freebsd_riscv64": _LD_FREEBSD_RISCV64,
    "freebsd_x86_32": _LD_FREEBSD_X86_32,
    "freebsd_x86_64": _LD_FREEBSD_X86_64,
    "fuchsia_aarch64": _LD_FUCHSIA_AARCH64,
    "fuchsia_riscv64": _LD_FUCHSIA_RISCV64,
    "fuchsia_x86_64": _LD_FUCHSIA_X86_64,
    "haiku_i386": _LD_HAIKU_X86_32,
    "haiku_x86_32": _LD_HAIKU_X86_32,
    "haiku_x86_64": _LD_HAIKU_X86_64,
    "linux_aarch32": _LD_LINUX_AARCH32,
    "linux_aarch64": _LD_LINUX_AARCH64,
    "linux_armv7": _LD_LINUX_ARMV7,
    "linux_i386": _LD_64_LINUX_X86_32,
    "linux_mips64": _LD_LINUX_MIPS64,
    "linux_ppc": _LD_LINUX_PPC,
    "linux_ppc32": _LD_64_LINUX_PPC32,
    "linux_ppc64le": _LD_LINUX_PPC64LE,
    "linux_riscv32": _LD_LINUX_RISCV32,
    "linux_riscv64": _LD_LINUX_RISCV64,
    "linux_s390x": _LD_LINUX_S390X,
    "linux_x86_32": _LD_64_LINUX_X86_32,
    "linux_x86_64": _LD_LINUX_X86_64,
    "macos_aarch64": None,
    "macos_x86_64": None,
    "netbsd_aarch32": _LD_NETBSD_AARCH32,
    "netbsd_aarch64": None,
    "netbsd_armv7": _LD_NETBSD_AARCH32,
    "netbsd_i386": _LD_NETBSD_X86_32,
    "netbsd_mips64": _LD_NETBSD_MIPS64,
    "netbsd_ppc": _LD_NETBSD_PPC,
    "netbsd_ppc32": _LD_64_NETBSD_PPC32,
    "netbsd_riscv64": _LD_NETBSD_RISCV64,
    "netbsd_x86_32": _LD_NETBSD_X86_32,
    "netbsd_x86_64": _LD_NETBSD_X86_64,
    "nixos_aarch32": _LD_LINUX_AARCH32,
    "nixos_aarch64": _LD_LINUX_AARCH64,
    "nixos_armv7": _LD_LINUX_ARMV7,
    "nixos_i386": _LD_64_LINUX_X86_32,
    "nixos_mips64": _LD_LINUX_MIPS64,
    "nixos_ppc": _LD_LINUX_PPC,
    "nixos_ppc32": _LD_64_LINUX_PPC32,
    "nixos_ppc64le": _LD_LINUX_PPC64LE,
    "nixos_riscv32": _LD_LINUX_RISCV32,
    "nixos_riscv64": _LD_LINUX_RISCV64,
    "nixos_s390x": _LD_LINUX_S390X,
    "nixos_x86_32": _LD_64_LINUX_X86_32,
    "nixos_x86_64": _LD_LINUX_X86_64,
    "openbsd_aarch32": None,
    "openbsd_aarch64": None,
    "openbsd_armv7": None,
    "openbsd_i386": _LD_OPENBSD_X86_32,
    "openbsd_mips64": _LD_OPENBSD_MIPS64,
    "openbsd_ppc": _LD_OPENBSD_PPC,
    "openbsd_ppc32": _LD_64_OPENBSD_PPC32,
    "openbsd_riscv64": _LD_OPENBSD_RISCV64,
    "openbsd_x86_32": _LD_OPENBSD_X86_32,
    "openbsd_x86_64": _LD_OPENBSD_X86_64,
    "qnx_aarch32": _LD_QNX_AARCH32,
    "qnx_aarch64": _LD_QNX_AARCH64,
    "qnx_armv7": _LD_QNX_AARCH32,
    "qnx_i386": _LD_QNX_X86_32,
    "qnx_ppc32": _LD_QNX_PPC32,
    "qnx_x86_32": _LD_QNX_X86_32,
    "vxworks_aarch32": _LD_VXWORKS_AARCH32,
    "vxworks_armv7": _LD_VXWORKS_AARCH32,
    "vxworks_i386": _LD_VXWORKS_X86_32,
    "vxworks_mips64": _LD_VXWORKS_MIPS64,
    "vxworks_ppc32": _LD_VXWORKS_PPC32,
    "vxworks_x86_32": _LD_VXWORKS_X86_32,
    "windows_aarch64": _LD_WINDOWS_AARCH64,
    "windows_i386": _LD_WINDOWS_X86_32,
    "windows_x86_32": _LD_WINDOWS_X86_32,
    "windows_x86_64": _LD_WINDOWS_X86_64,
}
