// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/ipi/fdt_ipi_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/ipi/fdt_ipi.h>

extern const struct fdt_driver fdt_ipi_mswi;
extern const struct fdt_driver fdt_ipi_plicsw;

const struct fdt_driver *const fdt_ipi_drivers[] = {
	&fdt_ipi_mswi,
	&fdt_ipi_plicsw,
	NULL
};
