/* Copied and modified from config.h by refresh-harfbuzz.sh */
/* Copied from config.h by refresh-harfbuzz.sh */
/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_ATEXIT 1

#define HAVE_CAIRO 1

/* #undef HAVE_CAIRO_FONT_OPTIONS_GET_CUSTOM_PALETTE_COLOR */

#define HAVE_CAIRO_FT 1

/* #undef HAVE_CAIRO_USER_FONT_FACE_SET_RENDER_COLOR_GLYPH_FUNC */

/* #undef HAVE_CAIRO_USER_SCALED_FONT_GET_FOREGROUND_SOURCE */

#if !defined(SUBSET)
#define HAVE_FREETYPE 1
#endif

/* #undef HAVE_FT_DONE_MM_VAR */

/* #undef HAVE_FT_GET_TRANSFORM */

#define HAVE_FT_GET_VAR_BLEND_COORDINATES 1

#define HAVE_FT_SET_VAR_BLEND_COORDINATES 1

#define HAVE_GETPAGESIZE 1

/* #undef HAVE_GLIB */

#define HAVE_GOBJECT 1

#define HAVE_GTK_DOC 1

/* #undef HAVE_ICU */

#define HAVE_ISATTY 1

#define HAVE_MMAP 1

#define HAVE_MPROTECT 1

#define HAVE_NEWLOCALE 1

#define HAVE_PTHREAD 1

/* #undef HAVE_SINCOSF */

#define HAVE_STDBOOL_H 1

#define HAVE_SYSCONF 1

#define HAVE_SYS_MMAN_H 1

#define HAVE_UNISTD_H 1

#define HAVE_USELOCALE 1

#define PACKAGE_NAME "HarfBuzz"

#define PACKAGE_VERSION "11.0.1"