# Maps rules used by googleapis to <flavor> if the rule is registered by the googleapis-<flavor>
# module or to None if the rule is not supported yet (some may never be).
RULE_TO_FLAVOR = {
    "cc_gapic_library": None,
    "cc_grpc_library": "grpc-cc",
    "cc_proto_library": "cc",
    "csharp_gapic_assembly_pkg": None,
    "csharp_gapic_library": None,
    "csharp_grpc_library": None,
    "csharp_proto_library": None,
    "go_gapic_assembly_pkg": None,
    "go_gapic_library": None,
    "go_grpc_library": None,
    "go_library": None,
    "go_proto_library": "go",
    "go_test": None,
    "java_gapic_assembly_gradle_pkg": None,
    "java_gapic_library": None,
    "java_gapic_test": None,
    "java_grpc_library": "grpc-java",
    "java_proto_library": "java",
    "moved_proto_library": None,
    "nodejs_gapic_assembly_pkg": None,
    "nodejs_gapic_library": None,
    "php_gapic_assembly_pkg": None,
    "php_gapic_library": None,
    "php_grpc_library": None,
    "php_proto_library": None,
    "proto_library_with_info": None,
    "py_gapic_assembly_pkg": None,
    "py_gapic_library": None,
    "py_grpc_library": None,
    "py_import": None,
    "py_proto_library": "python",
    "py_test": None,
    "ruby_ads_gapic_library": None,
    "ruby_cloud_gapic_library": None,
    "ruby_gapic_assembly_pkg": None,
    "ruby_grpc_library": None,
    "ruby_proto_library": None,
}

# The version of the googleapis-<flavor> modules to recommend to users.
FLAVOR_VERSION = "0.1.0"
