// Generated with carray.sh from /home/filmil/tmp/ai/opensbi/local/opensbi-src/lib/utils/suspend/fdt_suspend_drivers.carray
// DO NOT EDIT THIS FILE DIRECTLY

#include <sbi_utils/suspend/fdt_suspend.h>

extern const struct fdt_driver fdt_suspend_rpmi;

const struct fdt_driver *const fdt_suspend_drivers[] = {
	&fdt_suspend_rpmi,
	NULL
};
