# Copyright 2026 Open Source Robotics Foundation, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys

with open(sys.argv[1], "r") as f:
    lines = f.readlines()

print("/* Generated by Bazel */")
print("#ifndef TOKEN_NAMES_H_INCLUDED")
print("#define TOKEN_NAMES_H_INCLUDED")
print("const char *token_names[] = {")

for line in lines:
    line = line.strip()
    if line.startswith("CT_") and "," in line:
        name = line.split(",")[0].strip()[3:]
        print(f'   "{name}",')

print("};")
print("#endif")
