name: Review BCR Pull Requests
on:
  schedule:
    - cron: "0 * * * *"    # Run this action hourly
  workflow_dispatch:       # So that this can be triggered manually

jobs:
  review_prs:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Run BCR PR Review Approver
        uses: bazelbuild/continuous-integration/actions/bcr-pr-review-approver@b9b7f0dad8ab00a48cc262d1d38339a1dd11c7c5 # master
        with:
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
