name: Notify Module Maintainers For PR Review
on:
  pull_request:
    paths:
      - 'modules/**'

permissions:
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Run BCR PR Review Notifier
        uses: bazelbuild/continuous-integration/actions/bcr-pr-review-notifier@98021a23708b61580168002bdce84f459ac00750
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
