name: Generate module diff
on:
  pull_request:
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  generate_module_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Check out PR code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Generate module diff ( ⭐ 🔍 Expand here to see the diff ⭐)
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@4abfc06fbb6141560a439d4d3356f72f0a6caadd
        with:
          action-type: diff_module
