name: Notify Module Maintainers For PR Review
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  notify_maintainers:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Run BCR PR Reviewer
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@a2d20d30382ca5b42cb1554c206b2e3401ed5bc2 # master
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: notify_maintainers
