name: Notify Module Maintainers For PR Review
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  notify_maintainers:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Run BCR PR Reviewer
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@47d5ff02f7c1108d72b1d9182bf64d43ce2c539e # master
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: notify_maintainers
