name: Notify Module Maintainers For PR Review
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - 'modules/**'

jobs:
  notify_maintainers:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Run BCR PR Reviewer
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@2f5eb5523e74e297c3a7753bc7732b29f230460c # master
        with:
          # This token needs to be updated annually on Feb 05.
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: notify_maintainers
