name: skip_check
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  comment_bot:
    if: startsWith(github.event.comment.body, '@bazel-io skip_check ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Run bot
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@c02e506ebcaf204c4972142544608ac328f198a4 # master
        with:
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: skip_check
