name: skip_check
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  comment_bot:
    if: startsWith(github.event.comment.body, '@bazel-io skip_check ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Run bot
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@f7f428909585a8f6ba46d0b622f8aa93b6c263cc # master
        with:
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: skip_check
