name: skip_check
on:
  issue_comment:
    types: [created, edited]
permissions:
  contents: read

jobs:
  comment_bot:
    if: startsWith(github.event.comment.body, '@bazel-io skip_check ')
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Run bot
        uses: bazelbuild/continuous-integration/actions/bcr-pr-reviewer@3d8663cb5406076255c6865af23cb85d6eff5c35 # master
        with:
          token: ${{ secrets.BCR_PR_REVIEW_HELPER_TOKEN }}
          action-type: skip_check
