name: Sync BCR to Cloudflare R2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository == 'wheelos/bazel-central-registry'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'

      # - name: Install dependencies
      #   run: pip install requests

      # - name: Mirror Archives
      #   run: |
      #     python .github/scripts/mirror_archives.py

      - name: Sync to R2
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude '.git/*' --exclude '.github/*'
        env:
          AWS_S3_BUCKET: "wheelos-bazel-registry"
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: "https://${{ secrets.CF_ACCOUNT_ID }}.r2.cloudflarestorage.com"
          SOURCE_DIR: "."
