on:
  push:
    branches:
      - main
jobs:
  trigger_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build of BCR UI
        uses: peter-evans/repository-dispatch@v3
        with:
          repository: bazel-contrib/bcr-ui
          # Fine-grained PAT (https://github.com/settings/personal-access-tokens/new), which needs
          # to be exchanged once a year.
          # Scoped to the `bazel-contrib/bcr-ui` repository.
          # Requires "Read and write" permissions for "Contents" to be able to do the workflow dispatch.
          token: ${{ secrets.BCR_UI_REPO_ACCESS_TOKEN }}
          event-type: on-bcr-trigger
          client-payload: '{"bcrCommitHash": "${{ github.sha }}"}'
