name: Verify stable source URLs
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
      - run: python3 ./tools/verify_stable_archives.py
